<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActividadesEconomicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ciiu_codes = [
            ['codigo_ciiu' => '0111', 'descripcion' => 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas'],
            ['codigo_ciiu' => '0112', 'descripcion' => 'Cultivo de arroz'],
            ['codigo_ciiu' => '0113', 'descripcion' => 'Cultivo de hortalizas, raíces y tubérculos'],
            ['codigo_ciiu' => '0114', 'descripcion' => 'Cultivo de tabaco'],
            ['codigo_ciiu' => '0115', 'descripcion' => 'Cultivo de plantas textiles'],
            ['codigo_ciiu' => '0119', 'descripcion' => 'Otros cultivos transitorios n.c.p.'],
            ['codigo_ciiu' => '0121', 'descripcion' => 'Cultivo de frutas tropicales y subtropicales'],
            ['codigo_ciiu' => '0122', 'descripcion' => 'Cultivo de plátano y banano'],
            ['codigo_ciiu' => '0123', 'descripcion' => 'Cultivo de café'],
            ['codigo_ciiu' => '0124', 'descripcion' => 'Cultivo de caña de azúcar'],
            ['codigo_ciiu' => '0125', 'descripcion' => 'Cultivo de flor de corte'],
            ['codigo_ciiu' => '0126', 'descripcion' => 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos'],
            ['codigo_ciiu' => '0127', 'descripcion' => 'Cultivo de plantas con las que se preparan bebidas'],
            ['codigo_ciiu' => '0128', 'descripcion' => 'Cultivo de especias y de plantas aromáticas y medicinales'],
            ['codigo_ciiu' => '0129', 'descripcion' => 'Otros cultivos permanentes n.c.p.'],
            ['codigo_ciiu' => '0130', 'descripcion' => 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)'],
            ['codigo_ciiu' => '0141', 'descripcion' => 'Cría de ganado bovino y bufalino'],
            ['codigo_ciiu' => '0142', 'descripcion' => 'Cría de caballos y otros equinos'],
            ['codigo_ciiu' => '0143', 'descripcion' => 'Cría de ovejas y cabras'],
            ['codigo_ciiu' => '0144', 'descripcion' => 'Cría de ganado porcino'],
            ['codigo_ciiu' => '0145', 'descripcion' => 'Cría de aves de corral'],
            ['codigo_ciiu' => '0149', 'descripcion' => 'Cría de otros animales n.c.p.'],
            ['codigo_ciiu' => '0150', 'descripcion' => 'Explotación mixta (agrícola y pecuaria)'],
            ['codigo_ciiu' => '0161', 'descripcion' => 'Actividades de apoyo a la agricultura'],
            ['codigo_ciiu' => '0162', 'descripcion' => 'Actividades de apoyo a la ganadería'],
            ['codigo_ciiu' => '0163', 'descripcion' => 'Actividades posteriores a la cosecha'],
            ['codigo_ciiu' => '0164', 'descripcion' => 'Tratamiento de semillas para propagación'],
            ['codigo_ciiu' => '0170', 'descripcion' => 'Caza ordinaria y mediante trampas y actividades de servicios conexas'],
            ['codigo_ciiu' => '0210', 'descripcion' => 'Silvicultura y otras actividades forestales'],
            ['codigo_ciiu' => '0220', 'descripcion' => 'Extracción de madera'],
            ['codigo_ciiu' => '0230', 'descripcion' => 'Recolección de productos forestales diferentes a la madera'],
            ['codigo_ciiu' => '0240', 'descripcion' => 'Servicios de apoyo a la silvicultura'],
            ['codigo_ciiu' => '0311', 'descripcion' => 'Pesca marítima'],
            ['codigo_ciiu' => '0312', 'descripcion' => 'Pesca de agua dulce'],
            ['codigo_ciiu' => '0321', 'descripcion' => 'Acuicultura marítima'],
            ['codigo_ciiu' => '0322', 'descripcion' => 'Acuicultura de agua dulce'],
            ['codigo_ciiu' => '0510', 'descripcion' => 'Extracción de hulla (carbón de piedra)'],
            ['codigo_ciiu' => '0520', 'descripcion' => 'Extracción de carbón lignito'],
            ['codigo_ciiu' => '0610', 'descripcion' => 'Extracción de petróleo crudo'],
            ['codigo_ciiu' => '0620', 'descripcion' => 'Extracción de gas natural'],
            ['codigo_ciiu' => '0710', 'descripcion' => 'Extracción de minerales de hierro'],
            ['codigo_ciiu' => '0721', 'descripcion' => 'Extracción de minerales de uranio y de torio'],
            ['codigo_ciiu' => '0722', 'descripcion' => 'Extracción de oro y otros metales preciosos'],
            ['codigo_ciiu' => '0723', 'descripcion' => 'Extracción de minerales de níquel'],
            ['codigo_ciiu' => '0729', 'descripcion' => 'Extracción de otros minerales metalíferos no ferrosos n.c.p.'],
            ['codigo_ciiu' => '0811', 'descripcion' => 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita'],
            ['codigo_ciiu' => '0812', 'descripcion' => 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas'],
            ['codigo_ciiu' => '0820', 'descripcion' => 'Extracción de esmeraldas, piedras preciosas y semipreciosas'],
            ['codigo_ciiu' => '0891', 'descripcion' => 'Extracción de minerales para la fabricación de abonos y productos químicos'],
            ['codigo_ciiu' => '0892', 'descripcion' => 'Extracción de halita (sal)'],
            ['codigo_ciiu' => '0899', 'descripcion' => 'Extracción de otros minerales no metálicos n.c.p.'],
            ['codigo_ciiu' => '0910', 'descripcion' => 'Actividades de apoyo para la extracción de petróleo y de gas natural'],
            ['codigo_ciiu' => '0990', 'descripcion' => 'Actividades de apoyo para otras actividades de explotación de minas y canteras'],
            ['codigo_ciiu' => '1011', 'descripcion' => 'Procesamiento y conservación de carne y productos cárnicos'],
            ['codigo_ciiu' => '1012', 'descripcion' => 'Procesamiento y conservación de pescados, crustáceos y moluscos'],
            ['codigo_ciiu' => '1020', 'descripcion' => 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos'],
            ['codigo_ciiu' => '1030', 'descripcion' => 'Elaboración de aceites y grasas de origen vegetal y animal'],
            ['codigo_ciiu' => '1040', 'descripcion' => 'Elaboración de productos lácteos'],
            ['codigo_ciiu' => '1051', 'descripcion' => 'Elaboración de productos de molinería'],
            ['codigo_ciiu' => '1052', 'descripcion' => 'Elaboración de almidones y productos derivados del almidón'],
            ['codigo_ciiu' => '1061', 'descripcion' => 'Trilla de café'],
            ['codigo_ciiu' => '1062', 'descripcion' => 'Descafeinado, tostión y molienda del café'],
            ['codigo_ciiu' => '1063', 'descripcion' => 'Otros derivados del café'],
            ['codigo_ciiu' => '1071', 'descripcion' => 'Elaboración y refinación de azúcar'],
            ['codigo_ciiu' => '1072', 'descripcion' => 'Elaboración de panela'],
            ['codigo_ciiu' => '1081', 'descripcion' => 'Elaboración de productos de panadería'],
            ['codigo_ciiu' => '1082', 'descripcion' => 'Elaboración de cacao, chocolate y productos de confitería'],
            ['codigo_ciiu' => '1083', 'descripcion' => 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares'],
            ['codigo_ciiu' => '1084', 'descripcion' => 'Elaboración de comidas y platos preparados'],
            ['codigo_ciiu' => '1089', 'descripcion' => 'Elaboración de otros productos alimenticios n.c.p.'],
            ['codigo_ciiu' => '1090', 'descripcion' => 'Elaboración de alimentos preparados para animales'],
            ['codigo_ciiu' => '1101', 'descripcion' => 'Destilación, rectificación y mezcla de bebidas alcohólicas'],
            ['codigo_ciiu' => '1102', 'descripcion' => 'Elaboración de bebidas fermentadas no destiladas'],
            ['codigo_ciiu' => '1103', 'descripcion' => 'Producción de malta, elaboración de cervezas y otras bebidas malteadas'],
            ['codigo_ciiu' => '1104', 'descripcion' => 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas'],
            ['codigo_ciiu' => '1200', 'descripcion' => 'Elaboración de productos de tabaco'],
            ['codigo_ciiu' => '1311', 'descripcion' => 'Preparación e hilatura de fibras textiles'],
            ['codigo_ciiu' => '1312', 'descripcion' => 'Tejeduría de productos textiles'],
            ['codigo_ciiu' => '1313', 'descripcion' => 'Acabado de productos textiles'],
            ['codigo_ciiu' => '1391', 'descripcion' => 'Fabricación de tejidos de punto y ganchillo'],
            ['codigo_ciiu' => '1392', 'descripcion' => 'Confección de artículos con materiales textiles, excepto prendas de vestir'],
            ['codigo_ciiu' => '1393', 'descripcion' => 'Fabricación de tapetes y alfombras para pisos'],
            ['codigo_ciiu' => '1394', 'descripcion' => 'Fabricación de cuerdas, cordeles, cables, bramantes y redes'],
            ['codigo_ciiu' => '1399', 'descripcion' => 'Fabricación de otros artículos textiles n.c.p.'],
            ['codigo_ciiu' => '1410', 'descripcion' => 'Confección de prendas de vestir, excepto prendas de piel'],
            ['codigo_ciiu' => '1420', 'descripcion' => 'Fabricación de artículos de piel'],
            ['codigo_ciiu' => '1430', 'descripcion' => 'Fabricación de artículos de punto y ganchillo'],
            ['codigo_ciiu' => '1511', 'descripcion' => 'Curtido y recurtido de cueros; recurtido y teñido de pieles'],
            ['codigo_ciiu' => '1512', 'descripcion' => 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería'],
            ['codigo_ciiu' => '1513', 'descripcion' => 'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales'],
            ['codigo_ciiu' => '1521', 'descripcion' => 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela'],
            ['codigo_ciiu' => '1522', 'descripcion' => 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel'],
            ['codigo_ciiu' => '1523', 'descripcion' => 'Fabricación de partes del calzado'],
            ['codigo_ciiu' => '1610', 'descripcion' => 'Aserrado, acepillado e impregnación de la madera'],
            ['codigo_ciiu' => '1620', 'descripcion' => 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles'],
            ['codigo_ciiu' => '1630', 'descripcion' => 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción'],
            ['codigo_ciiu' => '1640', 'descripcion' => 'Fabricación de recipientes de madera'],
            ['codigo_ciiu' => '1690', 'descripcion' => 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería'],
            ['codigo_ciiu' => '1701', 'descripcion' => 'Fabricación de pulpas (pastas) celulósicas; papel y cartón'],
            ['codigo_ciiu' => '1702', 'descripcion' => 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón'],
            ['codigo_ciiu' => '1709', 'descripcion' => 'Fabricación de otros artículos de papel y cartón'],
            ['codigo_ciiu' => '1811', 'descripcion' => 'Actividades de impresión'],
            ['codigo_ciiu' => '1812', 'descripcion' => 'Actividades de servicios relacionados con la impresión'],
            ['codigo_ciiu' => '1820', 'descripcion' => 'Producción de copias a partir de grabaciones originales'],
            ['codigo_ciiu' => '1910', 'descripcion' => 'Fabricación de productos de hornos de coque'],
            ['codigo_ciiu' => '1921', 'descripcion' => 'Fabricación de productos de la refinación del petróleo'],
            ['codigo_ciiu' => '1922', 'descripcion' => 'Actividad de mezcla de combustibles'],
            ['codigo_ciiu' => '2011', 'descripcion' => 'Fabricación de sustancias y productos químicos básicos'],
            ['codigo_ciiu' => '2012', 'descripcion' => 'Fabricación de abonos y compuestos inorgánicos nitrogenados'],
            ['codigo_ciiu' => '2013', 'descripcion' => 'Fabricación de plásticos en formas primarias'],
            ['codigo_ciiu' => '2014', 'descripcion' => 'Fabricación de caucho sintético en formas primarias'],
            ['codigo_ciiu' => '2021', 'descripcion' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'],
            ['codigo_ciiu' => '2022', 'descripcion' => 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas'],
            ['codigo_ciiu' => '2023', 'descripcion' => 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador'],
            ['codigo_ciiu' => '2029', 'descripcion' => 'Fabricación de otros productos químicos n.c.p.'],
            ['codigo_ciiu' => '2030', 'descripcion' => 'Fabricación de fibras sintéticas y artificiales'],
            ['codigo_ciiu' => '2100', 'descripcion' => 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'],
            ['codigo_ciiu' => '2211', 'descripcion' => 'Fabricación de llantas y neumáticos de caucho'],
            ['codigo_ciiu' => '2212', 'descripcion' => 'Reencauche de llantas usadas'],
            ['codigo_ciiu' => '2219', 'descripcion' => 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.'],
            ['codigo_ciiu' => '2221', 'descripcion' => 'Fabricación de formas básicas de plástico'],
            ['codigo_ciiu' => '2229', 'descripcion' => 'Fabricación de artículos de plástico n.c.p.'],
            ['codigo_ciiu' => '2310', 'descripcion' => 'Fabricación de vidrio y productos de vidrio'],
            ['codigo_ciiu' => '2391', 'descripcion' => 'Fabricación de productos refractarios'],
            ['codigo_ciiu' => '2392', 'descripcion' => 'Fabricación de materiales de arcilla para la construcción'],
            ['codigo_ciiu' => '2393', 'descripcion' => 'Fabricación de otros productos de cerámica y porcelana'],
            ['codigo_ciiu' => '2394', 'descripcion' => 'Fabricación de cemento, cal y yeso'],
            ['codigo_ciiu' => '2395', 'descripcion' => 'Fabricación de artículos de hormigón, cemento y yeso'],
            ['codigo_ciiu' => '2396', 'descripcion' => 'Corte, tallado y acabado de la piedra'],
            ['codigo_ciiu' => '2399', 'descripcion' => 'Fabricación de otros productos minerales no metálicos n.c.p.'],
            ['codigo_ciiu' => '2410', 'descripcion' => 'Industrias básicas de hierro y de acero'],
            ['codigo_ciiu' => '2421', 'descripcion' => 'Industrias básicas de metales preciosos'],
            ['codigo_ciiu' => '2429', 'descripcion' => 'Industrias básicas de otros metales no ferrosos'],
            ['codigo_ciiu' => '2431', 'descripcion' => 'Fundición de hierro y de acero'],
            ['codigo_ciiu' => '2432', 'descripcion' => 'Fundición de metales no ferrosos'],
            ['codigo_ciiu' => '2511', 'descripcion' => 'Fabricación de productos metálicos para uso estructural'],
            ['codigo_ciiu' => '2512', 'descripcion' => 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías'],
            ['codigo_ciiu' => '2513', 'descripcion' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'],
            ['codigo_ciiu' => '2520', 'descripcion' => 'Fabricación de armas y municiones'],
            ['codigo_ciiu' => '2591', 'descripcion' => 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia'],
            ['codigo_ciiu' => '2592', 'descripcion' => 'Tratamiento y revestimiento de metales; mecanizado'],
            ['codigo_ciiu' => '2593', 'descripcion' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'],
            ['codigo_ciiu' => '2599', 'descripcion' => 'Fabricación de otros productos elaborados de metal n.c.p.'],
            ['codigo_ciiu' => '2610', 'descripcion' => 'Fabricación de componentes y tableros electrónicos'],
            ['codigo_ciiu' => '2620', 'descripcion' => 'Fabricación de computadoras y de equipo periférico'],
            ['codigo_ciiu' => '2630', 'descripcion' => 'Fabricación de equipos de comunicación'],
            ['codigo_ciiu' => '2640', 'descripcion' => 'Fabricación de aparatos electrónicos de consumo'],
            ['codigo_ciiu' => '2651', 'descripcion' => 'Fabricación de equipo de medición, prueba, navegación y control'],
            ['codigo_ciiu' => '2652', 'descripcion' => 'Fabricación de relojes'],
            ['codigo_ciiu' => '2660', 'descripcion' => 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico'],
            ['codigo_ciiu' => '2670', 'descripcion' => 'Fabricación de instrumentos ópticos y equipo fotográfico'],
            ['codigo_ciiu' => '2680', 'descripcion' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos'],
            ['codigo_ciiu' => '2711', 'descripcion' => 'Fabricación de motores, generadores y transformadores eléctricos'],
            ['codigo_ciiu' => '2712', 'descripcion' => 'Fabricación de aparatos de distribución y control de la energía eléctrica'],
            ['codigo_ciiu' => '2720', 'descripcion' => 'Fabricación de pilas, baterías y acumuladores eléctricos'],
            ['codigo_ciiu' => '2731', 'descripcion' => 'Fabricación de hilos y cables eléctricos y de fibra óptica'],
            ['codigo_ciiu' => '2732', 'descripcion' => 'Fabricación de dispositivos de cableado'],
            ['codigo_ciiu' => '2740', 'descripcion' => 'Fabricación de equipos eléctricos de iluminación'],
            ['codigo_ciiu' => '2750', 'descripcion' => 'Fabricación de aparatos de uso doméstico'],
            ['codigo_ciiu' => '2790', 'descripcion' => 'Fabricación de otros tipos de equipo eléctrico n.c.p.'],
            ['codigo_ciiu' => '2811', 'descripcion' => 'Fabricación de motores, turbinas, y partes para motores de combustión interna'],
            ['codigo_ciiu' => '2812', 'descripcion' => 'Fabricación de equipos de potencia hidráulica y neumática'],
            ['codigo_ciiu' => '2813', 'descripcion' => 'Fabricación de otras bombas, compresores, grifos y válvulas'],
            ['codigo_ciiu' => '2814', 'descripcion' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'],
            ['codigo_ciiu' => '2815', 'descripcion' => 'Fabricación de hornos, hogares y quemadores industriales'],
            ['codigo_ciiu' => '2816', 'descripcion' => 'Fabricación de equipo de elevación y manipulación'],
            ['codigo_ciiu' => '2817', 'descripcion' => 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)'],
            ['codigo_ciiu' => '2818', 'descripcion' => 'Fabricación de herramientas manuales con motor'],
            ['codigo_ciiu' => '2819', 'descripcion' => 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.'],
            ['codigo_ciiu' => '2821', 'descripcion' => 'Fabricación de maquinaria agropecuaria y forestal'],
            ['codigo_ciiu' => '2822', 'descripcion' => 'Fabricación de máquinas formadoras de metal y de máquinas herramienta'],
            ['codigo_ciiu' => '2823', 'descripcion' => 'Fabricación de maquinaria para la metalurgia'],
            ['codigo_ciiu' => '2824', 'descripcion' => 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción'],
            ['codigo_ciiu' => '2825', 'descripcion' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'],
            ['codigo_ciiu' => '2826', 'descripcion' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'],
            ['codigo_ciiu' => '2829', 'descripcion' => 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.'],
            ['codigo_ciiu' => '2910', 'descripcion' => 'Fabricación de vehículos automotores y sus motores'],
            ['codigo_ciiu' => '2920', 'descripcion' => 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques'],
            ['codigo_ciiu' => '2930', 'descripcion' => 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'],
            ['codigo_ciiu' => '3011', 'descripcion' => 'Construcción de barcos y de estructuras flotantes'],
            ['codigo_ciiu' => '3012', 'descripcion' => 'Construcción de embarcaciones de recreo y deporte'],
            ['codigo_ciiu' => '3020', 'descripcion' => 'Fabricación de locomotoras y de material rodante para ferrocarriles'],
            ['codigo_ciiu' => '3030', 'descripcion' => 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa'],
            ['codigo_ciiu' => '3040', 'descripcion' => 'Fabricación de vehículos militares de combate'],
            ['codigo_ciiu' => '3091', 'descripcion' => 'Fabricación de motocicletas'],
            ['codigo_ciiu' => '3092', 'descripcion' => 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad'],
            ['codigo_ciiu' => '3099', 'descripcion' => 'Fabricación de otros tipos de equipo de transporte n.c.p.'],
            ['codigo_ciiu' => '3110', 'descripcion' => 'Fabricación de muebles'],
            ['codigo_ciiu' => '3120', 'descripcion' => 'Fabricación de colchones y somieres'],
            ['codigo_ciiu' => '3210', 'descripcion' => 'Fabricación de joyas, bisutería y artículos conexos'],
            ['codigo_ciiu' => '3220', 'descripcion' => 'Fabricación de instrumentos musicales'],
            ['codigo_ciiu' => '3230', 'descripcion' => 'Fabricación de artículos y equipo para la práctica del deporte'],
            ['codigo_ciiu' => '3240', 'descripcion' => 'Fabricación de juegos, juguetes y rompecabezas'],
            ['codigo_ciiu' => '3250', 'descripcion' => 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)'],
            ['codigo_ciiu' => '3290', 'descripcion' => 'Otras industrias manufactureras n.c.p.'],
            ['codigo_ciiu' => '3311', 'descripcion' => 'Mantenimiento y reparación especializado de productos elaborados en metal'],
            ['codigo_ciiu' => '3312', 'descripcion' => 'Mantenimiento y reparación especializado de maquinaria y equipo'],
            ['codigo_ciiu' => '3313', 'descripcion' => 'Mantenimiento y reparación especializado de equipo electrónico y óptico'],
            ['codigo_ciiu' => '3314', 'descripcion' => 'Mantenimiento y reparación especializado de equipo eléctrico'],
            ['codigo_ciiu' => '3315', 'descripcion' => 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas'],
            ['codigo_ciiu' => '3319', 'descripcion' => 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.'],
            ['codigo_ciiu' => '3320', 'descripcion' => 'Instalación especializada de maquinaria y equipo industrial'],
            ['codigo_ciiu' => '3511', 'descripcion' => 'Generación de energía eléctrica'],
            ['codigo_ciiu' => '3512', 'descripcion' => 'Transmisión de energía eléctrica'],
            ['codigo_ciiu' => '3513', 'descripcion' => 'Distribución de energía eléctrica'],
            ['codigo_ciiu' => '3514', 'descripcion' => 'Comercialización de energía eléctrica'],
            ['codigo_ciiu' => '3520', 'descripcion' => 'Producción de gas; distribución de combustibles gaseosos por tuberías'],
            ['codigo_ciiu' => '3530', 'descripcion' => 'Suministro de vapor y aire acondicionado'],
            ['codigo_ciiu' => '3600', 'descripcion' => 'Captación, tratamiento y distribución de agua'],
            ['codigo_ciiu' => '3700', 'descripcion' => 'Evacuación y tratamiento de aguas residuales'],
            ['codigo_ciiu' => '3811', 'descripcion' => 'Recolección de desechos no peligrosos'],
            ['codigo_ciiu' => '3812', 'descripcion' => 'Recolección de desechos peligrosos'],
            ['codigo_ciiu' => '3821', 'descripcion' => 'Tratamiento y disposición de desechos no peligrosos'],
            ['codigo_ciiu' => '3822', 'descripcion' => 'Tratamiento y disposición de desechos peligrosos'],
            ['codigo_ciiu' => '3830', 'descripcion' => 'Recuperación de materiales'],
            ['codigo_ciiu' => '3900', 'descripcion' => 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'],
            ['codigo_ciiu' => '4111', 'descripcion' => 'Construcción de edificios residenciales'],
            ['codigo_ciiu' => '4112', 'descripcion' => 'Construcción de edificios no residenciales'],
            ['codigo_ciiu' => '4210', 'descripcion' => 'Construcción de carreteras y vías de ferrocarril'],
            ['codigo_ciiu' => '4220', 'descripcion' => 'Construcción de proyectos de servicio público'],
            ['codigo_ciiu' => '4290', 'descripcion' => 'Construcción de otras obras de ingeniería civil'],
            ['codigo_ciiu' => '4311', 'descripcion' => 'Demolición'],
            ['codigo_ciiu' => '4312', 'descripcion' => 'Preparación del terreno'],
            ['codigo_ciiu' => '4321', 'descripcion' => 'Instalaciones eléctricas'],
            ['codigo_ciiu' => '4322', 'descripcion' => 'Instalaciones de fontanería, calefacción y aire acondicionado'],
            ['codigo_ciiu' => '4329', 'descripcion' => 'Otras instalaciones especializadas'],
            ['codigo_ciiu' => '4330', 'descripcion' => 'Terminación y acabado de edificios y obras de ingeniería civil'],
            ['codigo_ciiu' => '4390', 'descripcion' => 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil'],
            ['codigo_ciiu' => '4511', 'descripcion' => 'Comercio de vehículos automotores nuevos'],
            ['codigo_ciiu' => '4512', 'descripcion' => 'Comercio de vehículos automotores usados'],
            ['codigo_ciiu' => '4520', 'descripcion' => 'Mantenimiento y reparación de vehículos automotores'],
            ['codigo_ciiu' => '4530', 'descripcion' => 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'],
            ['codigo_ciiu' => '4541', 'descripcion' => 'Comercio de motocicletas y de sus partes, piezas y accesorios'],
            ['codigo_ciiu' => '4542', 'descripcion' => 'Mantenimiento y reparación de motocicletas y de sus partes y piezas'],
            ['codigo_ciiu' => '4610', 'descripcion' => 'Comercio al por mayor a cambio de una retribución o por contrata'],
            ['codigo_ciiu' => '4620', 'descripcion' => 'Comercio al por mayor de materias primas agropecuarias; animales vivos'],
            ['codigo_ciiu' => '4631', 'descripcion' => 'Comercio al por mayor de productos alimenticios'],
            ['codigo_ciiu' => '4632', 'descripcion' => 'Comercio al por mayor de bebidas y tabaco'],
            ['codigo_ciiu' => '4641', 'descripcion' => 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico'],
            ['codigo_ciiu' => '4642', 'descripcion' => 'Comercio al por mayor de prendas de vestir'],
            ['codigo_ciiu' => '4643', 'descripcion' => 'Comercio al por mayor de calzado'],
            ['codigo_ciiu' => '4644', 'descripcion' => 'Comercio al por mayor de aparatos y equipo de uso doméstico'],
            ['codigo_ciiu' => '4645', 'descripcion' => 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador'],
            ['codigo_ciiu' => '4649', 'descripcion' => 'Comercio al por mayor de otros utensilios domésticos n.c.p.'],
            ['codigo_ciiu' => '4651', 'descripcion' => 'Comercio al por mayor de computadores, equipo periférico y programas de informática'],
            ['codigo_ciiu' => '4652', 'descripcion' => 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones'],
            ['codigo_ciiu' => '4653', 'descripcion' => 'Comercio al por mayor de maquinaria y equipo agropecuarios'],
            ['codigo_ciiu' => '4659', 'descripcion' => 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.'],
            ['codigo_ciiu' => '4661', 'descripcion' => 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos'],
            ['codigo_ciiu' => '4662', 'descripcion' => 'Comercio al por mayor de metales y productos metalíferos'],
            ['codigo_ciiu' => '4663', 'descripcion' => 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción'],
            ['codigo_ciiu' => '4664', 'descripcion' => 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario'],
            ['codigo_ciiu' => '4665', 'descripcion' => 'Comercio al por mayor de desperdicios, desechos y chatarra'],
            ['codigo_ciiu' => '4669', 'descripcion' => 'Comercio al por mayor de otros productos n.c.p.'],
            ['codigo_ciiu' => '4690', 'descripcion' => 'Comercio al por mayor no especializado'],
            ['codigo_ciiu' => '4711', 'descripcion' => 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco'],
            ['codigo_ciiu' => '4719', 'descripcion' => 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco'],
            ['codigo_ciiu' => '4721', 'descripcion' => 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados'],
            ['codigo_ciiu' => '4722', 'descripcion' => 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados'],
            ['codigo_ciiu' => '4723', 'descripcion' => 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados'],
            ['codigo_ciiu' => '4724', 'descripcion' => 'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados'],
            ['codigo_ciiu' => '4729', 'descripcion' => 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados'],
            ['codigo_ciiu' => '4731', 'descripcion' => 'Comercio al por menor de combustible para automotores'],
            ['codigo_ciiu' => '4732', 'descripcion' => 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores'],
            ['codigo_ciiu' => '4741', 'descripcion' => 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados'],
            ['codigo_ciiu' => '4742', 'descripcion' => 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados'],
            ['codigo_ciiu' => '4751', 'descripcion' => 'Comercio al por menor de productos textiles en establecimientos especializados'],
            ['codigo_ciiu' => '4752', 'descripcion' => 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados'],
            ['codigo_ciiu' => '4753', 'descripcion' => 'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados'],
            ['codigo_ciiu' => '4754', 'descripcion' => 'Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación'],
            ['codigo_ciiu' => '4755', 'descripcion' => 'Comercio al por menor de artículos y utensilios de uso doméstico'],
            ['codigo_ciiu' => '4759', 'descripcion' => 'Comercio al por menor de otros artículos domésticos en establecimientos especializados'],
            ['codigo_ciiu' => '4761', 'descripcion' => 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados'],
            ['codigo_ciiu' => '4762', 'descripcion' => 'Comercio al por menor de artículos deportivos, en establecimientos especializados'],
            ['codigo_ciiu' => '4769', 'descripcion' => 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados'],
            ['codigo_ciiu' => '4771', 'descripcion' => 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados'],
            ['codigo_ciiu' => '4772', 'descripcion' => 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados'],
            ['codigo_ciiu' => '4773', 'descripcion' => 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados'],
            ['codigo_ciiu' => '4774', 'descripcion' => 'Comercio al por menor de otros productos nuevos en establecimientos especializados'],
            ['codigo_ciiu' => '4775', 'descripcion' => 'Comercio al por menor de artículos de segunda mano'],
            ['codigo_ciiu' => '4781', 'descripcion' => 'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles'],
            ['codigo_ciiu' => '4782', 'descripcion' => 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles'],
            ['codigo_ciiu' => '4789', 'descripcion' => 'Comercio al por menor de otros productos en puestos de venta móviles'],
            ['codigo_ciiu' => '4791', 'descripcion' => 'Comercio al por menor realizado a través de Internet'],
            ['codigo_ciiu' => '4792', 'descripcion' => 'Comercio al por menor realizado a través de casas de venta o por correo'],
            ['codigo_ciiu' => '4799', 'descripcion' => 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados'],
            ['codigo_ciiu' => '4911', 'descripcion' => 'Transporte férreo de pasajeros'],
            ['codigo_ciiu' => '4912', 'descripcion' => 'Transporte férreo de carga'],
            ['codigo_ciiu' => '4921', 'descripcion' => 'Transporte de pasajeros'],
            ['codigo_ciiu' => '4922', 'descripcion' => 'Transporte mixto'],
            ['codigo_ciiu' => '4923', 'descripcion' => 'Transporte de carga por carretera'],
            ['codigo_ciiu' => '4930', 'descripcion' => 'Transporte por tuberías'],
            ['codigo_ciiu' => '5011', 'descripcion' => 'Transporte de pasajeros marítimo y de cabotaje'],
            ['codigo_ciiu' => '5012', 'descripcion' => 'Transporte de carga marítimo y de cabotaje'],
            ['codigo_ciiu' => '5021', 'descripcion' => 'Transporte fluvial de pasajeros'],
            ['codigo_ciiu' => '5022', 'descripcion' => 'Transporte fluvial de carga'],
            ['codigo_ciiu' => '5111', 'descripcion' => 'Transporte aéreo nacional de pasajeros'],
            ['codigo_ciiu' => '5112', 'descripcion' => 'Transporte aéreo internacional de pasajeros'],
            ['codigo_ciiu' => '5121', 'descripcion' => 'Transporte aéreo nacional de carga'],
            ['codigo_ciiu' => '5122', 'descripcion' => 'Transporte aéreo internacional de carga'],
            ['codigo_ciiu' => '5210', 'descripcion' => 'Almacenamiento y depósito'],
            ['codigo_ciiu' => '5221', 'descripcion' => 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre'],
            ['codigo_ciiu' => '5222', 'descripcion' => 'Actividades de puertos y servicios complementarios para el transporte acuático'],
            ['codigo_ciiu' => '5223', 'descripcion' => 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo'],
            ['codigo_ciiu' => '5224', 'descripcion' => 'Manipulación de carga'],
            ['codigo_ciiu' => '5229', 'descripcion' => 'Otras actividades complementarias al transporte'],
            ['codigo_ciiu' => '5310', 'descripcion' => 'Actividades postales nacionales'],
            ['codigo_ciiu' => '5320', 'descripcion' => 'Actividades de mensajería'],
            ['codigo_ciiu' => '5511', 'descripcion' => 'Alojamiento en hoteles'],
            ['codigo_ciiu' => '5512', 'descripcion' => 'Alojamiento en apartahoteles'],
            ['codigo_ciiu' => '5513', 'descripcion' => 'Alojamiento en centros vacacionales'],
            ['codigo_ciiu' => '5514', 'descripcion' => 'Alojamiento rural'],
            ['codigo_ciiu' => '5519', 'descripcion' => 'Otros tipos de alojamientos para visitantes'],
            ['codigo_ciiu' => '5520', 'descripcion' => 'Actividades de zonas de camping y parques para vehículos recreacionales'],
            ['codigo_ciiu' => '5530', 'descripcion' => 'Servicio por horas'],
            ['codigo_ciiu' => '5590', 'descripcion' => 'Otros tipos de alojamiento n.c.p.'],
            ['codigo_ciiu' => '5611', 'descripcion' => 'Expendio a la mesa de comidas preparadas'],
            ['codigo_ciiu' => '5612', 'descripcion' => 'Expendio por autoservicio de comidas preparadas'],
            ['codigo_ciiu' => '5613', 'descripcion' => 'Expendio de comidas preparadas en cafeterías'],
            ['codigo_ciiu' => '5619', 'descripcion' => 'Otros tipos de expendio de comidas preparadas n.c.p.'],
            ['codigo_ciiu' => '5621', 'descripcion' => 'Catering para eventos'],
            ['codigo_ciiu' => '5629', 'descripcion' => 'Actividades de otros servicios de comidas'],
            ['codigo_ciiu' => '5630', 'descripcion' => 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'],
            ['codigo_ciiu' => '5811', 'descripcion' => 'Edición de libros'],
            ['codigo_ciiu' => '5812', 'descripcion' => 'Edición de directorios y listas de correo'],
            ['codigo_ciiu' => '5813', 'descripcion' => 'Edición de periódicos, revistas y otras publicaciones periódicas'],
            ['codigo_ciiu' => '5819', 'descripcion' => 'Otros trabajos de edición'],
            ['codigo_ciiu' => '5820', 'descripcion' => 'Edición de programas de informática (software)'],
            ['codigo_ciiu' => '5911', 'descripcion' => 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo_ciiu' => '5912', 'descripcion' => 'Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo_ciiu' => '5913', 'descripcion' => 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo_ciiu' => '5914', 'descripcion' => 'Actividades de exhibición de películas cinematográficas y videos'],
            ['codigo_ciiu' => '5920', 'descripcion' => 'Actividades de grabación de sonido y edición de música'],
            ['codigo_ciiu' => '6010', 'descripcion' => 'Actividades de programación y transmisión en el servicio de radiodifusión sonora'],
            ['codigo_ciiu' => '6020', 'descripcion' => 'Actividades de programación y transmisión de televisión'],
            ['codigo_ciiu' => '6110', 'descripcion' => 'Actividades de telecomunicaciones alámbricas'],
            ['codigo_ciiu' => '6120', 'descripcion' => 'Actividades de telecomunicaciones inalámbricas'],
            ['codigo_ciiu' => '6130', 'descripcion' => 'Actividades de telecomunicación satelital'],
            ['codigo_ciiu' => '6190', 'descripcion' => 'Otras actividades de telecomunicaciones'],
            ['codigo_ciiu' => '6201', 'descripcion' => 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)'],
            ['codigo_ciiu' => '6202', 'descripcion' => 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas'],
            ['codigo_ciiu' => '6209', 'descripcion' => 'Otras actividades de tecnologías de información y actividades de servicios informáticos'],
            ['codigo_ciiu' => '6311', 'descripcion' => 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas'],
            ['codigo_ciiu' => '6312', 'descripcion' => 'Portales web'],
            ['codigo_ciiu' => '6391', 'descripcion' => 'Actividades de agencias de noticias'],
            ['codigo_ciiu' => '6399', 'descripcion' => 'Otras actividades de servicio de información n.c.p.'],
            ['codigo_ciiu' => '6411', 'descripcion' => 'Banco Central'],
            ['codigo_ciiu' => '6412', 'descripcion' => 'Bancos comerciales'],
            ['codigo_ciiu' => '6421', 'descripcion' => 'Actividades de las corporaciones financieras'],
            ['codigo_ciiu' => '6422', 'descripcion' => 'Actividades de las compañías de financiamiento'],
            ['codigo_ciiu' => '6423', 'descripcion' => 'Banca de segundo piso'],
            ['codigo_ciiu' => '6424', 'descripcion' => 'Actividades de las cooperativas financieras'],
            ['codigo_ciiu' => '6431', 'descripcion' => 'Fideicomisos, fondos y entidades financieras similares'],
            ['codigo_ciiu' => '6432', 'descripcion' => 'Fondos de cesantías'],
            ['codigo_ciiu' => '6491', 'descripcion' => 'Leasing financiero (arrendamiento financiero)'],
            ['codigo_ciiu' => '6492', 'descripcion' => 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario'],
            ['codigo_ciiu' => '6493', 'descripcion' => 'Actividades de compra de cartera o factoring'],
            ['codigo_ciiu' => '6494', 'descripcion' => 'Otras actividades de distribución de fondos'],
            ['codigo_ciiu' => '6495', 'descripcion' => 'Instituciones especiales oficiales'],
            ['codigo_ciiu' => '6496', 'descripcion' => 'Capitalización'],
            ['codigo_ciiu' => '6499', 'descripcion' => 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.'],
            ['codigo_ciiu' => '6511', 'descripcion' => 'Seguros generales'],
            ['codigo_ciiu' => '6512', 'descripcion' => 'Seguros de vida'],
            ['codigo_ciiu' => '6513', 'descripcion' => 'Reaseguros'],
            ['codigo_ciiu' => '6515', 'descripcion' => 'Seguros de salud'],
            ['codigo_ciiu' => '6521', 'descripcion' => 'Servicios de seguros sociales de salud'],
            ['codigo_ciiu' => '6522', 'descripcion' => 'Servicios de seguros sociales de riesgos profesionales'],
            ['codigo_ciiu' => '6523', 'descripcion' => 'Servicios de seguros sociales en riesgos familia'],
            ['codigo_ciiu' => '6531', 'descripcion' => 'Régimen de prima media con prestación definida (RPM)'],
            ['codigo_ciiu' => '6532', 'descripcion' => 'Régimen de ahorro individual (RAI)'],
            ['codigo_ciiu' => '6611', 'descripcion' => 'Administración de mercados financieros'],
            ['codigo_ciiu' => '6612', 'descripcion' => 'Corretaje de valores y de contratos de productos básicos'],
            ['codigo_ciiu' => '6613', 'descripcion' => 'Otras actividades relacionadas con el mercado de valores'],
            ['codigo_ciiu' => '6614', 'descripcion' => 'Actividades de las casas de cambio'],
            ['codigo_ciiu' => '6615', 'descripcion' => 'Actividades de los profesionales de compra y venta de divisas'],
            ['codigo_ciiu' => '6619', 'descripcion' => 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.'],
            ['codigo_ciiu' => '6621', 'descripcion' => 'Actividades de agentes y corredores de seguros'],
            ['codigo_ciiu' => '6629', 'descripcion' => 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares'],
            ['codigo_ciiu' => '6630', 'descripcion' => 'Actividades de administración de fondos'],
            ['codigo_ciiu' => '6810', 'descripcion' => 'Actividades inmobiliarias realizadas con bienes propios o arrendados'],
            ['codigo_ciiu' => '6820', 'descripcion' => 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'],
            ['codigo_ciiu' => '6910', 'descripcion' => 'Actividades jurídicas'],
            ['codigo_ciiu' => '6920', 'descripcion' => 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria'],
            ['codigo_ciiu' => '7010', 'descripcion' => 'Actividades de administración empresarial'],
            ['codigo_ciiu' => '7020', 'descripcion' => 'Actividades de consultoría de gestión'],
            ['codigo_ciiu' => '7111', 'descripcion' => 'Actividades de arquitectura'],
            ['codigo_ciiu' => '7112', 'descripcion' => 'Actividades de ingeniería y otras actividades conexas de consultoría técnica'],
            ['codigo_ciiu' => '7120', 'descripcion' => 'Ensayos y análisis técnicos'],
            ['codigo_ciiu' => '7210', 'descripcion' => 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'],
            ['codigo_ciiu' => '7220', 'descripcion' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'],
            ['codigo_ciiu' => '7310', 'descripcion' => 'Publicidad'],
            ['codigo_ciiu' => '7320', 'descripcion' => 'Estudios de mercado y realización de encuestas de opinión pública'],
            ['codigo_ciiu' => '7410', 'descripcion' => 'Actividades especializadas de diseño'],
            ['codigo_ciiu' => '7420', 'descripcion' => 'Actividades de fotografía'],
            ['codigo_ciiu' => '7490', 'descripcion' => 'Otras actividades profesionales, científicas y técnicas n.c.p.'],
            ['codigo_ciiu' => '7500', 'descripcion' => 'Actividades veterinarias'],
            ['codigo_ciiu' => '7710', 'descripcion' => 'Alquiler y arrendamiento de vehículos automotores'],
            ['codigo_ciiu' => '7721', 'descripcion' => 'Alquiler y arrendamiento de equipo recreativo y deportivo'],
            ['codigo_ciiu' => '7722', 'descripcion' => 'Alquiler de videos y discos'],
            ['codigo_ciiu' => '7729', 'descripcion' => 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.'],
            ['codigo_ciiu' => '7730', 'descripcion' => 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.'],
            ['codigo_ciiu' => '7740', 'descripcion' => 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'],
            ['codigo_ciiu' => '7810', 'descripcion' => 'Actividades de agencias de empleo'],
            ['codigo_ciiu' => '7820', 'descripcion' => 'Actividades de agencias de empleo temporal'],
            ['codigo_ciiu' => '7830', 'descripcion' => 'Otras actividades de suministro de recurso humano'],
            ['codigo_ciiu' => '7911', 'descripcion' => 'Actividades de las agencias de viaje'],
            ['codigo_ciiu' => '7912', 'descripcion' => 'Actividades de operadores turísticos'],
            ['codigo_ciiu' => '7990', 'descripcion' => 'Otros servicios de reserva y actividades relacionadas'],
            ['codigo_ciiu' => '8010', 'descripcion' => 'Actividades de seguridad privada'],
            ['codigo_ciiu' => '8020', 'descripcion' => 'Actividades de servicios de sistemas de seguridad'],
            ['codigo_ciiu' => '8030', 'descripcion' => 'Actividades de detectives e investigadores privados'],
            ['codigo_ciiu' => '8110', 'descripcion' => 'Actividades combinadas de apoyo a instalaciones'],
            ['codigo_ciiu' => '8121', 'descripcion' => 'Limpieza general interior de edificios'],
            ['codigo_ciiu' => '8129', 'descripcion' => 'Otras actividades de limpieza de edificios e instalaciones industriales'],
            ['codigo_ciiu' => '8130', 'descripcion' => 'Actividades de paisajismo y servicios de mantenimiento conexos'],
            ['codigo_ciiu' => '8211', 'descripcion' => 'Actividades combinadas de servicios administrativos de oficina'],
            ['codigo_ciiu' => '8219', 'descripcion' => 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina'],
            ['codigo_ciiu' => '8220', 'descripcion' => 'Actividades de centros de llamadas (Call center)'],
            ['codigo_ciiu' => '8230', 'descripcion' => 'Organización de convenciones y eventos comerciales'],
            ['codigo_ciiu' => '8291', 'descripcion' => 'Actividades de agencias de cobranza y oficinas de calificación crediticia'],
            ['codigo_ciiu' => '8292', 'descripcion' => 'Actividades de envase y empaque'],
            ['codigo_ciiu' => '8299', 'descripcion' => 'Otras actividades de servicio de apoyo a las empresas n.c.p.'],
            ['codigo_ciiu' => '8411', 'descripcion' => 'Actividades legislativas de la administración pública'],
            ['codigo_ciiu' => '8412', 'descripcion' => 'Actividades ejecutivas de la administración pública'],
            ['codigo_ciiu' => '8413', 'descripcion' => 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social'],
            ['codigo_ciiu' => '8414', 'descripcion' => 'Actividades reguladoras y facilitadoras de la actividad económica'],
            ['codigo_ciiu' => '8415', 'descripcion' => 'Actividades de los otros órganos de control'],
            ['codigo_ciiu' => '8421', 'descripcion' => 'Relaciones exteriores'],
            ['codigo_ciiu' => '8422', 'descripcion' => 'Actividades de defensa'],
            ['codigo_ciiu' => '8423', 'descripcion' => 'Orden público y actividades de seguridad'],
            ['codigo_ciiu' => '8424', 'descripcion' => 'Administración de justicia'],
            ['codigo_ciiu' => '8430', 'descripcion' => 'Actividades de planes de seguridad social de afiliación obligatoria'],
            ['codigo_ciiu' => '8511', 'descripcion' => 'Educación de la primera infancia'],
            ['codigo_ciiu' => '8512', 'descripcion' => 'Educación preescolar'],
            ['codigo_ciiu' => '8513', 'descripcion' => 'Educación básica primaria'],
            ['codigo_ciiu' => '8521', 'descripcion' => 'Educación básica secundaria'],
            ['codigo_ciiu' => '8522', 'descripcion' => 'Educación media académica'],
            ['codigo_ciiu' => '8523', 'descripcion' => 'Educación media técnica y de formación laboral'],
            ['codigo_ciiu' => '8530', 'descripcion' => 'Establecimientos que combinan diferentes niveles de educación'],
            ['codigo_ciiu' => '8541', 'descripcion' => 'Educación técnica profesional'],
            ['codigo_ciiu' => '8542', 'descripcion' => 'Educación tecnológica'],
            ['codigo_ciiu' => '8543', 'descripcion' => 'Educación de instituciones universitarias o de escuelas tecnológicas'],
            ['codigo_ciiu' => '8544', 'descripcion' => 'Educación de universidades'],
            ['codigo_ciiu' => '8551', 'descripcion' => 'Formación académica no formal'],
            ['codigo_ciiu' => '8552', 'descripcion' => 'Enseñanza deportiva y recreativa'],
            ['codigo_ciiu' => '8553', 'descripcion' => 'Enseñanza cultural'],
            ['codigo_ciiu' => '8559', 'descripcion' => 'Otros tipos de educación n.c.p.'],
            ['codigo_ciiu' => '8560', 'descripcion' => 'Actividades de apoyo a la educación'],
            ['codigo_ciiu' => '8610', 'descripcion' => 'Actividades de hospitales y clínicas, con internación'],
            ['codigo_ciiu' => '8621', 'descripcion' => 'Actividades de la práctica médica, sin internación'],
            ['codigo_ciiu' => '8622', 'descripcion' => 'Actividades de la práctica odontológica'],
            ['codigo_ciiu' => '8691', 'descripcion' => 'Actividades de apoyo diagnóstico'],
            ['codigo_ciiu' => '8692', 'descripcion' => 'Actividades de apoyo terapéutico'],
            ['codigo_ciiu' => '8699', 'descripcion' => 'Otras actividades de atención de la salud humana'],
            ['codigo_ciiu' => '8710', 'descripcion' => 'Actividades de atención residencial medicalizada de tipo general'],
            ['codigo_ciiu' => '8720', 'descripcion' => 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas'],
            ['codigo_ciiu' => '8730', 'descripcion' => 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas'],
            ['codigo_ciiu' => '8790', 'descripcion' => 'Otras actividades de atención en instituciones con alojamiento'],
            ['codigo_ciiu' => '8810', 'descripcion' => 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas'],
            ['codigo_ciiu' => '8891', 'descripcion' => 'Actividades de guarderías para niños y niñas'],
            ['codigo_ciiu' => '8899', 'descripcion' => 'Otras actividades de asistencia social sin alojamiento n.c.p.'],
            ['codigo_ciiu' => '9001', 'descripcion' => 'Creación literaria'],
            ['codigo_ciiu' => '9002', 'descripcion' => 'Creación musical'],
            ['codigo_ciiu' => '9003', 'descripcion' => 'Creación teatral'],
            ['codigo_ciiu' => '9004', 'descripcion' => 'Creación audiovisual'],
            ['codigo_ciiu' => '9005', 'descripcion' => 'Artes plásticas y visuales'],
            ['codigo_ciiu' => '9006', 'descripcion' => 'Actividades teatrales'],
            ['codigo_ciiu' => '9007', 'descripcion' => 'Actividades de espectáculos musicales en vivo'],
            ['codigo_ciiu' => '9008', 'descripcion' => 'Otras actividades de espectáculos en vivo'],
            ['codigo_ciiu' => '9101', 'descripcion' => 'Actividades de bibliotecas y archivos'],
            ['codigo_ciiu' => '9102', 'descripcion' => 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos'],
            ['codigo_ciiu' => '9103', 'descripcion' => 'Actividades de jardines botánicos, zoológicos y reservas naturales'],
            ['codigo_ciiu' => '9200', 'descripcion' => 'Actividades de juegos de azar y apuestas'],
            ['codigo_ciiu' => '9311', 'descripcion' => 'Gestión de instalaciones deportivas'],
            ['codigo_ciiu' => '9312', 'descripcion' => 'Actividades de clubes deportivos'],
            ['codigo_ciiu' => '9319', 'descripcion' => 'Otras actividades deportivas'],
            ['codigo_ciiu' => '9321', 'descripcion' => 'Actividades de parques de atracciones y parques temáticos'],
            ['codigo_ciiu' => '9329', 'descripcion' => 'Otras actividades recreativas y de esparcimiento n.c.p.'],
            ['codigo_ciiu' => '9411', 'descripcion' => 'Actividades de asociaciones empresariales y de empleadores'],
            ['codigo_ciiu' => '9412', 'descripcion' => 'Actividades de asociaciones profesionales'],
            ['codigo_ciiu' => '9420', 'descripcion' => 'Actividades de sindicatos de empleados'],
            ['codigo_ciiu' => '9491', 'descripcion' => 'Actividades de asociaciones religiosas'],
            ['codigo_ciiu' => '9492', 'descripcion' => 'Actividades de asociaciones políticas'],
            ['codigo_ciiu' => '9499', 'descripcion' => 'Actividades de otras asociaciones n.c.p.'],
            ['codigo_ciiu' => '9511', 'descripcion' => 'Mantenimiento y reparación de computadores y de equipo periférico'],
            ['codigo_ciiu' => '9512', 'descripcion' => 'Mantenimiento y reparación de equipos de comunicación'],
            ['codigo_ciiu' => '9521', 'descripcion' => 'Mantenimiento y reparación de aparatos electrónicos de consumo'],
            ['codigo_ciiu' => '9522', 'descripcion' => 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería'],
            ['codigo_ciiu' => '9523', 'descripcion' => 'Reparación de calzado y artículos de cuero'],
            ['codigo_ciiu' => '9524', 'descripcion' => 'Reparación de muebles y accesorios para el hogar'],
            ['codigo_ciiu' => '9529', 'descripcion' => 'Mantenimiento y reparación de otros efectos personales y enseres domésticos'],
            ['codigo_ciiu' => '9601', 'descripcion' => 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel'],
            ['codigo_ciiu' => '9602', 'descripcion' => 'Peluquería y otros tratamientos de belleza'],
            ['codigo_ciiu' => '9603', 'descripcion' => 'Pompas fúnebres y actividades relacionadas'],
            ['codigo_ciiu' => '9609', 'descripcion' => 'Otras actividades de servicios personales n.c.p.'],
            ['codigo_ciiu' => '9700', 'descripcion' => 'Actividades de los hogares individuales como empleadores de personal doméstico'],
            ['codigo_ciiu' => '9810', 'descripcion' => 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio'],
            ['codigo_ciiu' => '9820', 'descripcion' => 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio'],
            ['codigo_ciiu' => '9900', 'descripcion' => 'Actividades de organizaciones y entidades extraterritoriales'],
            ['codigo_ciiu' => '0010', 'descripcion' => 'Asalariados'],
            ['codigo_ciiu' => '0020', 'descripcion' => 'Pensionados'],
            ['codigo_ciiu' => '0081', 'descripcion' => 'Personas Naturales sin Actividad Económica'],
            ['codigo_ciiu' => '0082', 'descripcion' => 'Personas Naturales Subsidiadas por Terceros'],
            ['codigo_ciiu' => '0090', 'descripcion' => 'Rentistas de Capital, solo para personas naturales']

        ];
        
        

        DB::table('actividades_economicas')->insert($ciiu_codes);
    }
}
