<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $ciudades = [
            // ['codigo_dian' => '05001', 'nombre' => 'Medellín'],
            // ['codigo_dian' => '05002', 'nombre' => 'Abejorral'],
            // ['codigo_dian' => '05004', 'nombre' => 'Abriaquí'],
            // ['codigo_dian' => '05021', 'nombre' => 'Alejandría'],
            // ['codigo_dian' => '05030', 'nombre' => 'Amagá'],
            // ['codigo_dian' => '05031', 'nombre' => 'Amalfi'],
            // ['codigo_dian' => '05034', 'nombre' => 'Andes'],
            // ['codigo_dian' => '05036', 'nombre' => 'Angelópolis'],
            // ['codigo_dian' => '05038', 'nombre' => 'Angostura'],
            // ['codigo_dian' => '05040', 'nombre' => 'Anorí'],
            // ['codigo_dian' => '05042', 'nombre' => 'Santafé de Antioquia'],
            // ['codigo_dian' => '05044', 'nombre' => 'Anzá'],
            // ['codigo_dian' => '05045', 'nombre' => 'Apartadó'],
            // ['codigo_dian' => '05051', 'nombre' => 'Arboletes'],
            // ['codigo_dian' => '05055', 'nombre' => 'Argelia'],
            // ['codigo_dian' => '05059', 'nombre' => 'Armenia'],
            // ['codigo_dian' => '05079', 'nombre' => 'Barbosa'],
            // ['codigo_dian' => '05086', 'nombre' => 'Belmira'],
            // ['codigo_dian' => '05088', 'nombre' => 'Bello'],
            // ['codigo_dian' => '05091', 'nombre' => 'Betania'],
            // ['codigo_dian' => '05093', 'nombre' => 'Betulia'],
            // ['codigo_dian' => '05101', 'nombre' => 'Ciudad Bolívar'],
            // ['codigo_dian' => '05107', 'nombre' => 'Briceño'],
            // ['codigo_dian' => '05113', 'nombre' => 'Buriticá'],
            // ['codigo_dian' => '05120', 'nombre' => 'Cáceres'],
            // ['codigo_dian' => '05125', 'nombre' => 'Caicedo'],
            // ['codigo_dian' => '05129', 'nombre' => 'Caldas'],
            // ['codigo_dian' => '05134', 'nombre' => 'Campamento'],
            // ['codigo_dian' => '05138', 'nombre' => 'Cañasgordas'],
            // ['codigo_dian' => '05142', 'nombre' => 'Caracolí'],
            // ['codigo_dian' => '05145', 'nombre' => 'Caramanta'],
            // ['codigo_dian' => '05147', 'nombre' => 'Carepa'],
            // ['codigo_dian' => '05148', 'nombre' => 'El Carmen de Viboral'],
            // ['codigo_dian' => '05150', 'nombre' => 'Carolina del Príncipe'],
            // ['codigo_dian' => '05154', 'nombre' => 'Caucasia'],
            // ['codigo_dian' => '05172', 'nombre' => 'Chigorodó'],
            // ['codigo_dian' => '05190', 'nombre' => 'Cisneros'],
            // ['codigo_dian' => '05197', 'nombre' => 'Cocorná'],
            // ['codigo_dian' => '05206', 'nombre' => 'Concepción'],
            // ['codigo_dian' => '05209', 'nombre' => 'Concordia'],
            // ['codigo_dian' => '05212', 'nombre' => 'Copacabana'],
            // ['codigo_dian' => '05234', 'nombre' => 'Dabeiba'],
            // ['codigo_dian' => '05237', 'nombre' => 'Donmatías'],
            // ['codigo_dian' => '05240', 'nombre' => 'Ebéjico'],
            // ['codigo_dian' => '05250', 'nombre' => 'El Bagre'],
            // ['codigo_dian' => '05264', 'nombre' => 'Entrerríos'],
            // ['codigo_dian' => '05266', 'nombre' => 'Envigado'],
            // ['codigo_dian' => '05282', 'nombre' => 'Fredonia'],
            // ['codigo_dian' => '05284', 'nombre' => 'Frontino'],
            // ['codigo_dian' => '05306', 'nombre' => 'Giraldo'],
            // ['codigo_dian' => '05308', 'nombre' => 'Girardota'],
            // ['codigo_dian' => '05310', 'nombre' => 'Gómez Plata'],
            // ['codigo_dian' => '05313', 'nombre' => 'Granada'],
            // ['codigo_dian' => '05315', 'nombre' => 'Guadalupe'],
            // ['codigo_dian' => '05318', 'nombre' => 'Guarne'],
            // ['codigo_dian' => '05321', 'nombre' => 'Guatapé'],
            // ['codigo_dian' => '05347', 'nombre' => 'Heliconia'],
            // ['codigo_dian' => '05353', 'nombre' => 'Hispania'],
            // ['codigo_dian' => '05360', 'nombre' => 'Itagüí'],
            // ['codigo_dian' => '05361', 'nombre' => 'Ituango'],
            // ['codigo_dian' => '05364', 'nombre' => 'Jardín'],
            // ['codigo_dian' => '05368', 'nombre' => 'Jericó'],
            // ['codigo_dian' => '05376', 'nombre' => 'La Ceja'],
            // ['codigo_dian' => '05380', 'nombre' => 'La Estrella'],
            // ['codigo_dian' => '05390', 'nombre' => 'La Pintada'],
            // ['codigo_dian' => '05400', 'nombre' => 'La Unión'],
            // ['codigo_dian' => '05411', 'nombre' => 'Liborina'],
            // ['codigo_dian' => '05425', 'nombre' => 'Maceo'],
            // ['codigo_dian' => '05440', 'nombre' => 'Marinilla'],
            // ['codigo_dian' => '05467', 'nombre' => 'Montebello'],
            // ['codigo_dian' => '05475', 'nombre' => 'Murindó'],
            // ['codigo_dian' => '05480', 'nombre' => 'Mutatá'],
            // ['codigo_dian' => '05483', 'nombre' => 'Nariño'],
            // ['codigo_dian' => '05490', 'nombre' => 'Necoclí'],
            // ['codigo_dian' => '05495', 'nombre' => 'Nechí'],
            // ['codigo_dian' => '05501', 'nombre' => 'Olaya'],
            // ['codigo_dian' => '05541', 'nombre' => 'Peñol'],
            // ['codigo_dian' => '05543', 'nombre' => 'Peque'],
            // ['codigo_dian' => '05576', 'nombre' => 'Pueblorrico'],
            // ['codigo_dian' => '05579', 'nombre' => 'Puerto Berrío'],
            // ['codigo_dian' => '05585', 'nombre' => 'Puerto Nare'],
            // ['codigo_dian' => '05591', 'nombre' => 'Puerto Triunfo'],
            // ['codigo_dian' => '05604', 'nombre' => 'Remedios'],
            // ['codigo_dian' => '05607', 'nombre' => 'Retiro'],
            // ['codigo_dian' => '05615', 'nombre' => 'Rionegro'],
            // ['codigo_dian' => '05628', 'nombre' => 'Sabanalarga'],
            // ['codigo_dian' => '05631', 'nombre' => 'Sabaneta'],
            // ['codigo_dian' => '05642', 'nombre' => 'Salgar'],
            // ['codigo_dian' => '05647', 'nombre' => 'San Andrés de Cuerquía'],
            // ['codigo_dian' => '05649', 'nombre' => 'San Carlos'],
            // ['codigo_dian' => '05652', 'nombre' => 'San Francisco'],
            // ['codigo_dian' => '05656', 'nombre' => 'San Jerónimo'],
            // ['codigo_dian' => '05658', 'nombre' => 'San José de la Montaña'],
            // ['codigo_dian' => '05659', 'nombre' => 'San Juan de Urabá'],
            // ['codigo_dian' => '05660', 'nombre' => 'San Luis'],
            // ['codigo_dian' => '05664', 'nombre' => 'San Pedro de Urabá'],
            // ['codigo_dian' => '05665', 'nombre' => 'San Pedro de los Milagros'],
            // ['codigo_dian' => '05667', 'nombre' => 'San Rafael'],
            // ['codigo_dian' => '05670', 'nombre' => 'San Roque'],
            // ['codigo_dian' => '05674', 'nombre' => 'San Vicente Ferrer'],
            // ['codigo_dian' => '05679', 'nombre' => 'Santa Bárbara'],
            // ['codigo_dian' => '05686', 'nombre' => 'Santa Rosa de Osos'],
            // ['codigo_dian' => '05690', 'nombre' => 'Santo Domingo'],
            // ['codigo_dian' => '05697', 'nombre' => 'El Santuario'],
            // ['codigo_dian' => '05736', 'nombre' => 'Segovia'],
            // ['codigo_dian' => '05756', 'nombre' => 'Sonsón'],
            // ['codigo_dian' => '05761', 'nombre' => 'Sopetrán'],
            // ['codigo_dian' => '05789', 'nombre' => 'Támesis'],
            // ['codigo_dian' => '05790', 'nombre' => 'Tarazá'],
            // ['codigo_dian' => '05792', 'nombre' => 'Tarso'],
            // ['codigo_dian' => '05809', 'nombre' => 'Titiribí'],

        //AMAZONAS
            ['codigo_dian' => '91001', 'nombre' => 'Leticia'],
            ['codigo_dian' => '91263', 'nombre' => 'El Encanto'],
            ['codigo_dian' => '91405', 'nombre' => 'La Chorrera'],
            ['codigo_dian' => '91407', 'nombre' => 'La Pedrera'],
            ['codigo_dian' => '91430', 'nombre' => 'La Victoria'],
            ['codigo_dian' => '91460', 'nombre' => 'Miriti – Paraná'],
            ['codigo_dian' => '91530', 'nombre' => 'Puerto Alegría'],
            ['codigo_dian' => '91536', 'nombre' => 'Puerto Arica'],
            ['codigo_dian' => '91540', 'nombre' => 'Puerto Nariño'],
            ['codigo_dian' => '91669', 'nombre' => 'Puerto Santander'],
            ['codigo_dian' => '91798', 'nombre' => 'Tarapacá'],
        //ANTIOQUIA
            ['codigo_dian' => '5001', 'nombre' => 'Medellín'],
            ['codigo_dian' => '5002', 'nombre' => 'Abejorral'],
            ['codigo_dian' => '5004', 'nombre' => 'Abriaquí'],
            ['codigo_dian' => '5021', 'nombre' => 'Alejandría'],
            ['codigo_dian' => '5030', 'nombre' => 'Amagá'],
            ['codigo_dian' => '5031', 'nombre' => 'Amalfi'],
            ['codigo_dian' => '5034', 'nombre' => 'Andes'],
            ['codigo_dian' => '5036', 'nombre' => 'Angelópolis'],
            ['codigo_dian' => '5038', 'nombre' => 'Angostura'],
            ['codigo_dian' => '5040', 'nombre' => 'Anorí'],
            ['codigo_dian' => '5042', 'nombre' => 'Santafé De Antioquia'],
            ['codigo_dian' => '5044', 'nombre' => 'Anza'],
            ['codigo_dian' => '5045', 'nombre' => 'Apartadó'],
            ['codigo_dian' => '5051', 'nombre' => 'Arboletes'],
            ['codigo_dian' => '5055', 'nombre' => 'Argelia'],
            ['codigo_dian' => '5059', 'nombre' => 'Armenia'],
            ['codigo_dian' => '5079', 'nombre' => 'Barbosa'],
            ['codigo_dian' => '5086', 'nombre' => 'Belmira'],
            ['codigo_dian' => '5088', 'nombre' => 'Bello'],
            ['codigo_dian' => '5091', 'nombre' => 'Betania'],
            ['codigo_dian' => '5093', 'nombre' => 'Betulia'],
            ['codigo_dian' => '5101', 'nombre' => 'Ciudad Bolívar'],
            ['codigo_dian' => '5107', 'nombre' => 'Briceño'],
            ['codigo_dian' => '5113', 'nombre' => 'Buriticá'],
            ['codigo_dian' => '5120', 'nombre' => 'Cáceres'],
            ['codigo_dian' => '5125', 'nombre' => 'Caicedo'],
            ['codigo_dian' => '5129', 'nombre' => 'Caldas'],
            ['codigo_dian' => '5134', 'nombre' => 'Campamento'],
            ['codigo_dian' => '5138', 'nombre' => 'Cañasgordas'],
            ['codigo_dian' => '5142', 'nombre' => 'Caracolí'],
            ['codigo_dian' => '5145', 'nombre' => 'Caramanta'],
            ['codigo_dian' => '5147', 'nombre' => 'Carepa'],
            ['codigo_dian' => '5148', 'nombre' => 'El Carmen De Viboral'],
            ['codigo_dian' => '5150', 'nombre' => 'Carolina'],
            ['codigo_dian' => '5154', 'nombre' => 'Caucasia'],
            ['codigo_dian' => '5172', 'nombre' => 'Chigorodó'],
            ['codigo_dian' => '5190', 'nombre' => 'Cisneros'],
            ['codigo_dian' => '5197', 'nombre' => 'Cocorná'],
            ['codigo_dian' => '5206', 'nombre' => 'Concepción'],
            ['codigo_dian' => '5209', 'nombre' => 'Concordia'],
            ['codigo_dian' => '5212', 'nombre' => 'Copacabana'],
            ['codigo_dian' => '5234', 'nombre' => 'Dabeiba'],
            ['codigo_dian' => '5237', 'nombre' => 'Donmatías'],
            ['codigo_dian' => '5240', 'nombre' => 'Ebéjico'],
            ['codigo_dian' => '5250', 'nombre' => 'El Bagre'],
            ['codigo_dian' => '5264', 'nombre' => 'Entrerrios'],
            ['codigo_dian' => '5266', 'nombre' => 'Envigado'],
            ['codigo_dian' => '5282', 'nombre' => 'Fredonia'],
            ['codigo_dian' => '5284', 'nombre' => 'Frontino'],
            ['codigo_dian' => '5306', 'nombre' => 'Giraldo'],
            ['codigo_dian' => '5308', 'nombre' => 'Girardota'],
            ['codigo_dian' => '5310', 'nombre' => 'Gómez Plata'],
            ['codigo_dian' => '5313', 'nombre' => 'Granada'],
            ['codigo_dian' => '5315', 'nombre' => 'Guadalupe'],
            ['codigo_dian' => '5318', 'nombre' => 'Guarne'],
            ['codigo_dian' => '5321', 'nombre' => 'Guatape'],
            ['codigo_dian' => '5347', 'nombre' => 'Heliconia'],
            ['codigo_dian' => '5353', 'nombre' => 'Hispania'],
            ['codigo_dian' => '5360', 'nombre' => 'Itagui'],
            ['codigo_dian' => '5361', 'nombre' => 'Ituango'],
            ['codigo_dian' => '5364', 'nombre' => 'Jardín'],
            ['codigo_dian' => '5368', 'nombre' => 'Jericó'],
            ['codigo_dian' => '5376', 'nombre' => 'La Ceja'],
            ['codigo_dian' => '5380', 'nombre' => 'La Estrella'],
            ['codigo_dian' => '5390', 'nombre' => 'La Pintada'],
            ['codigo_dian' => '5400', 'nombre' => 'La Unión'],
            ['codigo_dian' => '5411', 'nombre' => 'Liborina'],
            ['codigo_dian' => '5425', 'nombre' => 'Maceo'],
            ['codigo_dian' => '5440', 'nombre' => 'Marinilla'],
            ['codigo_dian' => '5467', 'nombre' => 'Montebello'],
            ['codigo_dian' => '5475', 'nombre' => 'Murindó'],
            ['codigo_dian' => '5480', 'nombre' => 'Mutatá'],
            ['codigo_dian' => '5483', 'nombre' => 'Nariño'],
            ['codigo_dian' => '5490', 'nombre' => 'Necoclí'],
            ['codigo_dian' => '5495', 'nombre' => 'Nechí'],
            ['codigo_dian' => '5501', 'nombre' => 'Olaya'],
            ['codigo_dian' => '5541', 'nombre' => 'Peñol'],
            ['codigo_dian' => '5543', 'nombre' => 'Peque'],
            ['codigo_dian' => '5576', 'nombre' => 'Pueblorrico'],
            ['codigo_dian' => '5579', 'nombre' => 'Puerto Berrío'],
            ['codigo_dian' => '5585', 'nombre' => 'Puerto Nare'],
            ['codigo_dian' => '5591', 'nombre' => 'Puerto Triunfo'],
            ['codigo_dian' => '5604', 'nombre' => 'Remedios'],
            ['codigo_dian' => '5607', 'nombre' => 'Retiro'],
            ['codigo_dian' => '5615', 'nombre' => 'Rionegro'],
            ['codigo_dian' => '5628', 'nombre' => 'Sabanalarga'],
            ['codigo_dian' => '5631', 'nombre' => 'Sabaneta'],
            ['codigo_dian' => '5642', 'nombre' => 'Salgar'],
            ['codigo_dian' => '5647', 'nombre' => 'San Andrés De Cuerquía'],
            ['codigo_dian' => '5649', 'nombre' => 'San Carlos'],
            ['codigo_dian' => '5652', 'nombre' => 'San Francisco'],
            ['codigo_dian' => '5656', 'nombre' => 'San Jerónimo'],
            ['codigo_dian' => '5658', 'nombre' => 'San José De La Montaña'],
            ['codigo_dian' => '5659', 'nombre' => 'San Juan De Urabá'],
            ['codigo_dian' => '5660', 'nombre' => 'San Luis'],
            ['codigo_dian' => '5664', 'nombre' => 'San Pedro De Los Milagros'],
            ['codigo_dian' => '5665', 'nombre' => 'San Pedro De Uraba'],
            ['codigo_dian' => '5667', 'nombre' => 'San Rafael'],
            ['codigo_dian' => '5670', 'nombre' => 'San Roque'],
            ['codigo_dian' => '5674', 'nombre' => 'San Vicente'],
            ['codigo_dian' => '5679', 'nombre' => 'Santa Bárbara'],
            ['codigo_dian' => '5686', 'nombre' => 'Santa Rosa De Osos'],
            ['codigo_dian' => '5690', 'nombre' => 'Santo Domingo'],
            ['codigo_dian' => '5697', 'nombre' => 'El Santuario'],
            ['codigo_dian' => '5736', 'nombre' => 'Segovia'],
            ['codigo_dian' => '5756', 'nombre' => 'Sonson'],
            ['codigo_dian' => '5761', 'nombre' => 'Sopetrán'],
            ['codigo_dian' => '5789', 'nombre' => 'Támesis'],
            ['codigo_dian' => '5790', 'nombre' => 'Tarazá'],
            ['codigo_dian' => '5792', 'nombre' => 'Tarso'],
            ['codigo_dian' => '5809', 'nombre' => 'Titiribí'],
            ['codigo_dian' => '5819', 'nombre' => 'Toledo'],
            ['codigo_dian' => '5837', 'nombre' => 'Turbo'],
            ['codigo_dian' => '5842', 'nombre' => 'Uramita'],
            ['codigo_dian' => '5847', 'nombre' => 'Urrao'],
            ['codigo_dian' => '5854', 'nombre' => 'Valdivia'],
            ['codigo_dian' => '5856', 'nombre' => 'Valparaíso'],
            ['codigo_dian' => '5858', 'nombre' => 'Vegachí'],
            ['codigo_dian' => '5861', 'nombre' => 'Venecia'],
            ['codigo_dian' => '5873', 'nombre' => 'Vigía Del Fuerte'],
            ['codigo_dian' => '5885', 'nombre' => 'Yalí'],
            ['codigo_dian' => '5887', 'nombre' => 'Yarumal'],
            ['codigo_dian' => '5890', 'nombre' => 'Yolombó'],
            ['codigo_dian' => '5893', 'nombre' => 'Yondó'],
            ['codigo_dian' => '5895', 'nombre' => 'Zaragoza'],
        //ARAUCA
            ['codigo_dian' => '81001', 'nombre' => 'Arauca'],
            ['codigo_dian' => '81065', 'nombre' => 'Arauquita'],
            ['codigo_dian' => '81220', 'nombre' => 'Cravo Norte'],
            ['codigo_dian' => '81300', 'nombre' => 'Fortul'],
            ['codigo_dian' => '81591', 'nombre' => 'Puerto Rondón'],
            ['codigo_dian' => '81736', 'nombre' => 'Saravena'],
            ['codigo_dian' => '81794', 'nombre' => 'Tame'],
        //ATLANTICO
            ['codigo_dian' => '8001', 'nombre' => 'Barranquilla'],
            ['codigo_dian' => '8078', 'nombre' => 'Baranoa'],
            ['codigo_dian' => '8137', 'nombre' => 'Campo De La Cruz'],
            ['codigo_dian' => '8141', 'nombre' => 'Candelaria'],
            ['codigo_dian' => '8296', 'nombre' => 'Galapa'],
            ['codigo_dian' => '8372', 'nombre' => 'Juan De Acosta'],
            ['codigo_dian' => '8421', 'nombre' => 'Luruaco'],
            ['codigo_dian' => '8433', 'nombre' => 'Malambo'],
            ['codigo_dian' => '8436', 'nombre' => 'Manatí'],
            ['codigo_dian' => '8520', 'nombre' => 'Palmar De Varela'],
            ['codigo_dian' => '8549', 'nombre' => 'Piojó'],
            ['codigo_dian' => '8558', 'nombre' => 'Polonuevo'],
            ['codigo_dian' => '8560', 'nombre' => 'Ponedera'],
            ['codigo_dian' => '8573', 'nombre' => 'Puerto Colombia'],
            ['codigo_dian' => '8606', 'nombre' => 'Repelón'],
            ['codigo_dian' => '8634', 'nombre' => 'Sabanagrande'],
            ['codigo_dian' => '8638', 'nombre' => 'Sabanalarga'],
            ['codigo_dian' => '8675', 'nombre' => 'Santa Lucía'],
            ['codigo_dian' => '8685', 'nombre' => 'Santo Tomás'],
            ['codigo_dian' => '8758', 'nombre' => 'Soledad'],
            ['codigo_dian' => '8770', 'nombre' => 'Suan'],
            ['codigo_dian' => '8832', 'nombre' => 'Tubará'],
            ['codigo_dian' => '8849', 'nombre' => 'Usiacurí'],
        //BOGOTA
            ['codigo_dian' => '11001', 'nombre' => 'Bogotá, D.C.'],
        //BOLIVAR
            ['codigo_dian' => '13001', 'nombre' => 'Cartagena'],
            ['codigo_dian' => '13006', 'nombre' => 'Achí'],
            ['codigo_dian' => '13030', 'nombre' => 'Altos Del Rosario'],
            ['codigo_dian' => '13042', 'nombre' => 'Arenal'],
            ['codigo_dian' => '13052', 'nombre' => 'Arjona'],
            ['codigo_dian' => '13062', 'nombre' => 'Arroyohondo'],
            ['codigo_dian' => '13074', 'nombre' => 'Barranco De Loba'],
            ['codigo_dian' => '13140', 'nombre' => 'Calamar'],
            ['codigo_dian' => '13160', 'nombre' => 'Cantagallo'],
            ['codigo_dian' => '13188', 'nombre' => 'Cicuco'],
            ['codigo_dian' => '13212', 'nombre' => 'Córdoba'],
            ['codigo_dian' => '13222', 'nombre' => 'Clemencia'],
            ['codigo_dian' => '13244', 'nombre' => 'El Carmen De Bolívar'],
            ['codigo_dian' => '13248', 'nombre' => 'El Guamo'],
            ['codigo_dian' => '13268', 'nombre' => 'El Peñón'],
            ['codigo_dian' => '13300', 'nombre' => 'Hatillo De Loba'],
            ['codigo_dian' => '13430', 'nombre' => 'Magangué'],
            ['codigo_dian' => '13433', 'nombre' => 'Mahates'],
            ['codigo_dian' => '13440', 'nombre' => 'Margarita'],
            ['codigo_dian' => '13442', 'nombre' => 'María La Baja'],
            ['codigo_dian' => '13458', 'nombre' => 'Montecristo'],
            ['codigo_dian' => '13468', 'nombre' => 'Mompós'],
            ['codigo_dian' => '13473', 'nombre' => 'Morales'],
            ['codigo_dian' => '13490', 'nombre' => 'Norosí'],
            ['codigo_dian' => '13549', 'nombre' => 'Pinillos'],
            ['codigo_dian' => '13580', 'nombre' => 'Regidor'],
            ['codigo_dian' => '13600', 'nombre' => 'Río Viejo'],
            ['codigo_dian' => '13620', 'nombre' => 'San Cristóbal'],
            ['codigo_dian' => '13647', 'nombre' => 'San Estanislao'],
            ['codigo_dian' => '13650', 'nombre' => 'San Fernando'],
            ['codigo_dian' => '13654', 'nombre' => 'San Jacinto'],
            ['codigo_dian' => '13655', 'nombre' => 'San Jacinto Del Cauca'],
            ['codigo_dian' => '13657', 'nombre' => 'San Juan Nepomuceno'],
            ['codigo_dian' => '13667', 'nombre' => 'San Martín De Loba'],
            ['codigo_dian' => '13670', 'nombre' => 'San Pablo'],
            ['codigo_dian' => '13673', 'nombre' => 'Santa Catalina'],
            ['codigo_dian' => '13683', 'nombre' => 'Santa Rosa'],
            ['codigo_dian' => '13688', 'nombre' => 'Santa Rosa Del Sur'],
            ['codigo_dian' => '13744', 'nombre' => 'Simití'],
            ['codigo_dian' => '13760', 'nombre' => 'Soplaviento'],
            ['codigo_dian' => '13780', 'nombre' => 'Talaigua Nuevo'],
            ['codigo_dian' => '13810', 'nombre' => 'Tiquisio'],
            ['codigo_dian' => '13836', 'nombre' => 'Turbaco'],
            ['codigo_dian' => '13838', 'nombre' => 'Turbaná'],
            ['codigo_dian' => '13873', 'nombre' => 'Villanueva'],
            ['codigo_dian' => '13894', 'nombre' => 'Zambrano'],
        //BOYACA
            ['codigo_dian' => '15001', 'nombre' => 'Tunja'],
            ['codigo_dian' => '15022', 'nombre' => 'Almeida'],
            ['codigo_dian' => '15047', 'nombre' => 'Aquitania'],
            ['codigo_dian' => '15051', 'nombre' => 'Arcabuco'],
            ['codigo_dian' => '15087', 'nombre' => 'Belén'],
            ['codigo_dian' => '15090', 'nombre' => 'Berbeo'],
            ['codigo_dian' => '15092', 'nombre' => 'Betéitiva'],
            ['codigo_dian' => '15097', 'nombre' => 'Boavita'],
            ['codigo_dian' => '15104', 'nombre' => 'Boyacá'],
            ['codigo_dian' => '15106', 'nombre' => 'Briceño'],
            ['codigo_dian' => '15109', 'nombre' => 'Buenavista'],
            ['codigo_dian' => '15114', 'nombre' => 'Busbanzá'],
            ['codigo_dian' => '15131', 'nombre' => 'Caldas'],
            ['codigo_dian' => '15135', 'nombre' => 'Campohermoso'],
            ['codigo_dian' => '15162', 'nombre' => 'Cerinza'],
            ['codigo_dian' => '15172', 'nombre' => 'Chinavita'],
            ['codigo_dian' => '15176', 'nombre' => 'Chiquinquirá'],
            ['codigo_dian' => '15180', 'nombre' => 'Chiscas'],
            ['codigo_dian' => '15183', 'nombre' => 'Chita'],
            ['codigo_dian' => '15185', 'nombre' => 'Chitaraque'],
            ['codigo_dian' => '15187', 'nombre' => 'Chivatá'],
            ['codigo_dian' => '15189', 'nombre' => 'Ciénega'],
            ['codigo_dian' => '15204', 'nombre' => 'Cómbita'],
            ['codigo_dian' => '15212', 'nombre' => 'Coper'],
            ['codigo_dian' => '15215', 'nombre' => 'Corrales'],
            ['codigo_dian' => '15218', 'nombre' => 'Covarachía'],
            ['codigo_dian' => '15223', 'nombre' => 'Cubará'],
            ['codigo_dian' => '15224', 'nombre' => 'Cucaita'],
            ['codigo_dian' => '15226', 'nombre' => 'Cuítiva'],
            ['codigo_dian' => '15232', 'nombre' => 'Chíquiza'],
            ['codigo_dian' => '15236', 'nombre' => 'Chivor'],
            ['codigo_dian' => '15238', 'nombre' => 'Duitama'],
            ['codigo_dian' => '15244', 'nombre' => 'El Cocuy'],
            ['codigo_dian' => '15248', 'nombre' => 'El Espino'],
            ['codigo_dian' => '15272', 'nombre' => 'Firavitoba'],
            ['codigo_dian' => '15276', 'nombre' => 'Floresta'],
            ['codigo_dian' => '15293', 'nombre' => 'Gachantivá'],
            ['codigo_dian' => '15296', 'nombre' => 'Gameza'],
            ['codigo_dian' => '15299', 'nombre' => 'Garagoa'],
            ['codigo_dian' => '15317', 'nombre' => 'Guacamayas'],
            ['codigo_dian' => '15322', 'nombre' => 'Guateque'],
            ['codigo_dian' => '15325', 'nombre' => 'Guayatá'],
            ['codigo_dian' => '15332', 'nombre' => 'Güicán'],
            ['codigo_dian' => '15362', 'nombre' => 'Iza'],
            ['codigo_dian' => '15367', 'nombre' => 'Jenesano'],
            ['codigo_dian' => '15368', 'nombre' => 'Jericó'],
            ['codigo_dian' => '15377', 'nombre' => 'Labranzagrande'],
            ['codigo_dian' => '15380', 'nombre' => 'La Capilla'],
            ['codigo_dian' => '15401', 'nombre' => 'La Victoria'],
            ['codigo_dian' => '15403', 'nombre' => 'La Uvita'],
            ['codigo_dian' => '15407', 'nombre' => 'Villa De Leyva'],
            ['codigo_dian' => '15425', 'nombre' => 'Macanal'],
            ['codigo_dian' => '15442', 'nombre' => 'Maripí'],
            ['codigo_dian' => '15455', 'nombre' => 'Miraflores'],
            ['codigo_dian' => '15464', 'nombre' => 'Mongua'],
            ['codigo_dian' => '15466', 'nombre' => 'Monguí'],
            ['codigo_dian' => '15469', 'nombre' => 'Moniquirá'],
            ['codigo_dian' => '15476', 'nombre' => 'Motavita'],
            ['codigo_dian' => '15480', 'nombre' => 'Muzo'],
            ['codigo_dian' => '15491', 'nombre' => 'Nobsa'],
            ['codigo_dian' => '15494', 'nombre' => 'Nuevo Colón'],
            ['codigo_dian' => '15500', 'nombre' => 'Oicatá'],
            ['codigo_dian' => '15507', 'nombre' => 'Otanche'],
            ['codigo_dian' => '15511', 'nombre' => 'Pachavita'],
            ['codigo_dian' => '15514', 'nombre' => 'Páez'],
            ['codigo_dian' => '15516', 'nombre' => 'Paipa'],
            ['codigo_dian' => '15518', 'nombre' => 'Pajarito'],
            ['codigo_dian' => '15522', 'nombre' => 'Panqueba'],
            ['codigo_dian' => '15531', 'nombre' => 'Pauna'],
            ['codigo_dian' => '15533', 'nombre' => 'Paya'],
            ['codigo_dian' => '15537', 'nombre' => 'Paz De Río'],
            ['codigo_dian' => '15542', 'nombre' => 'Pesca'],
            ['codigo_dian' => '15550', 'nombre' => 'Pisba'],
            ['codigo_dian' => '15572', 'nombre' => 'Puerto Boyacá'],
            ['codigo_dian' => '15580', 'nombre' => 'Quípama'],
            ['codigo_dian' => '15599', 'nombre' => 'Ramiriquí'],
            ['codigo_dian' => '15600', 'nombre' => 'Ráquira'],
            ['codigo_dian' => '15621', 'nombre' => 'Rondón'],
            ['codigo_dian' => '15632', 'nombre' => 'Saboyá'],
            ['codigo_dian' => '15638', 'nombre' => 'Sáchica'],
            ['codigo_dian' => '15646', 'nombre' => 'Samacá'],
            ['codigo_dian' => '15660', 'nombre' => 'San Eduardo'],
            ['codigo_dian' => '15664', 'nombre' => 'San José De Pare'],
            ['codigo_dian' => '15667', 'nombre' => 'San Luis De Gaceno'],
            ['codigo_dian' => '15673', 'nombre' => 'San Mateo'],
            ['codigo_dian' => '15676', 'nombre' => 'San Miguel De Sema'],
            ['codigo_dian' => '15681', 'nombre' => 'San Pablo De Borbur'],
            ['codigo_dian' => '15686', 'nombre' => 'Santana'],
            ['codigo_dian' => '15690', 'nombre' => 'Santa María'],
            ['codigo_dian' => '15693', 'nombre' => 'Santa Rosa De Viterbo'],
            ['codigo_dian' => '15696', 'nombre' => 'Santa Sofía'],
            ['codigo_dian' => '15720', 'nombre' => 'Sativanorte'],
            ['codigo_dian' => '15723', 'nombre' => 'Sativasur'],
            ['codigo_dian' => '15740', 'nombre' => 'Siachoque'],
            ['codigo_dian' => '15753', 'nombre' => 'Soatá'],
            ['codigo_dian' => '15755', 'nombre' => 'Socotá'],
            ['codigo_dian' => '15757', 'nombre' => 'Socha'],
            ['codigo_dian' => '15759', 'nombre' => 'Sogamoso'],
            ['codigo_dian' => '15761', 'nombre' => 'Somondoco'],
            ['codigo_dian' => '15762', 'nombre' => 'Sora'],
            ['codigo_dian' => '15763', 'nombre' => 'Sotaquirá'],
            ['codigo_dian' => '15764', 'nombre' => 'Soracá'],
            ['codigo_dian' => '15774', 'nombre' => 'Susacón'],
            ['codigo_dian' => '15776', 'nombre' => 'Sutamarchán'],
            ['codigo_dian' => '15778', 'nombre' => 'Sutatenza'],
            ['codigo_dian' => '15790', 'nombre' => 'Tasco'],
            ['codigo_dian' => '15798', 'nombre' => 'Tenza'],
            ['codigo_dian' => '15804', 'nombre' => 'Tibaná'],
            ['codigo_dian' => '15806', 'nombre' => 'Tibasosa'],
            ['codigo_dian' => '15808', 'nombre' => 'Tinjacá'],
            ['codigo_dian' => '15810', 'nombre' => 'Tipacoque'],
            ['codigo_dian' => '15814', 'nombre' => 'Toca'],
            ['codigo_dian' => '15816', 'nombre' => 'Togüí'],
            ['codigo_dian' => '15820', 'nombre' => 'Tópaga'],
            ['codigo_dian' => '15822', 'nombre' => 'Tota'],
            ['codigo_dian' => '15832', 'nombre' => 'Tununguá'],
            ['codigo_dian' => '15835', 'nombre' => 'Turmequé'],
            ['codigo_dian' => '15837', 'nombre' => 'Tuta'],
            ['codigo_dian' => '15839', 'nombre' => 'Tutazá'],
            ['codigo_dian' => '15842', 'nombre' => 'Umbita'],
            ['codigo_dian' => '15861', 'nombre' => 'Ventaquemada'],
            ['codigo_dian' => '15879', 'nombre' => 'Viracachá'],
            ['codigo_dian' => '15897', 'nombre' => 'Zetaquira'],
        //CALDAS
            ['codigo_dian' => '17001', 'nombre' => 'Manizales'],
            ['codigo_dian' => '17013', 'nombre' => 'Aguadas'],
            ['codigo_dian' => '17042', 'nombre' => 'Anserma'],
            ['codigo_dian' => '17050', 'nombre' => 'Aranzazu'],
            ['codigo_dian' => '17088', 'nombre' => 'Belalcázar'],
            ['codigo_dian' => '17174', 'nombre' => 'Chinchiná'],
            ['codigo_dian' => '17272', 'nombre' => 'Filadelfia'],
            ['codigo_dian' => '17380', 'nombre' => 'La Dorada'],
            ['codigo_dian' => '17388', 'nombre' => 'La Merced'],
            ['codigo_dian' => '17433', 'nombre' => 'Manzanares'],
            ['codigo_dian' => '17442', 'nombre' => 'Marmato'],
            ['codigo_dian' => '17444', 'nombre' => 'Marquetalia'],
            ['codigo_dian' => '17446', 'nombre' => 'Marulanda'],
            ['codigo_dian' => '17486', 'nombre' => 'Neira'],
            ['codigo_dian' => '17495', 'nombre' => 'Norcasia'],
            ['codigo_dian' => '17513', 'nombre' => 'Pácora'],
            ['codigo_dian' => '17524', 'nombre' => 'Palestina'],
            ['codigo_dian' => '17541', 'nombre' => 'Pensilvania'],
            ['codigo_dian' => '17614', 'nombre' => 'Riosucio'],
            ['codigo_dian' => '17616', 'nombre' => 'Risaralda'],
            ['codigo_dian' => '17653', 'nombre' => 'Salamina'],
            ['codigo_dian' => '17662', 'nombre' => 'Samaná'],
            ['codigo_dian' => '17665', 'nombre' => 'San José'],
            ['codigo_dian' => '17777', 'nombre' => 'Supía'],
            ['codigo_dian' => '17867', 'nombre' => 'Victoria'],
            ['codigo_dian' => '17873', 'nombre' => 'Villamaría'],
            ['codigo_dian' => '17877', 'nombre' => 'Viterbo'],
        //CAQUETA
            ['codigo_dian' => '18001', 'nombre' => 'Florencia'],
            ['codigo_dian' => '18029', 'nombre' => 'Albania'],
            ['codigo_dian' => '18094', 'nombre' => 'Belén De Los Andaquíes'],
            ['codigo_dian' => '18150', 'nombre' => 'Cartagena Del Chairá'],
            ['codigo_dian' => '18205', 'nombre' => 'Curillo'],
            ['codigo_dian' => '18247', 'nombre' => 'El Doncello'],
            ['codigo_dian' => '18256', 'nombre' => 'El Paujil'],
            ['codigo_dian' => '18410', 'nombre' => 'La Montañita'],
            ['codigo_dian' => '18460', 'nombre' => 'Milán'],
            ['codigo_dian' => '18479', 'nombre' => 'Morelia'],
            ['codigo_dian' => '18592', 'nombre' => 'Puerto Rico'],
            ['codigo_dian' => '18610', 'nombre' => 'San José Del Fragua'],
            ['codigo_dian' => '18753', 'nombre' => 'San Vicente Del Caguán'],
            ['codigo_dian' => '18756', 'nombre' => 'Solano'],
            ['codigo_dian' => '18785', 'nombre' => 'Solita'],
            ['codigo_dian' => '18860', 'nombre' => 'Valparaíso'],
        //CASANARE
            ['codigo_dian' => '85001', 'nombre' => 'Yopal'],
            ['codigo_dian' => '85010', 'nombre' => 'Aguazul'],
            ['codigo_dian' => '85015', 'nombre' => 'Chameza'],
            ['codigo_dian' => '85125', 'nombre' => 'Hato Corozal'],
            ['codigo_dian' => '85136', 'nombre' => 'La Salina'],
            ['codigo_dian' => '85139', 'nombre' => 'Maní'],
            ['codigo_dian' => '85162', 'nombre' => 'Monterrey'],
            ['codigo_dian' => '85225', 'nombre' => 'Nunchía'],
            ['codigo_dian' => '85230', 'nombre' => 'Orocué'],
            ['codigo_dian' => '85250', 'nombre' => 'Paz De Ariporo'],
            ['codigo_dian' => '85263', 'nombre' => 'Pore'],
            ['codigo_dian' => '85279', 'nombre' => 'Recetor'],
            ['codigo_dian' => '85300', 'nombre' => 'Sabanalarga'],
            ['codigo_dian' => '85315', 'nombre' => 'Sácama'],
            ['codigo_dian' => '85325', 'nombre' => 'San Luis De Palenque'],
            ['codigo_dian' => '85400', 'nombre' => 'Támara'],
            ['codigo_dian' => '85410', 'nombre' => 'Tauramena'],
            ['codigo_dian' => '85430', 'nombre' => 'Trinidad'],
            ['codigo_dian' => '85440', 'nombre' => 'Villanueva'],
        //CAUCA
            ['codigo_dian' => '19001', 'nombre' => 'Popayán'],
            ['codigo_dian' => '19022', 'nombre' => 'Almaguer'],
            ['codigo_dian' => '19050', 'nombre' => 'Argelia'],
            ['codigo_dian' => '19075', 'nombre' => 'Balboa'],
            ['codigo_dian' => '19100', 'nombre' => 'Bolívar'],
            ['codigo_dian' => '19110', 'nombre' => 'Buenos Aires'],
            ['codigo_dian' => '19130', 'nombre' => 'Cajibío'],
            ['codigo_dian' => '19137', 'nombre' => 'Caldono'],
            ['codigo_dian' => '19142', 'nombre' => 'Caloto'],
            ['codigo_dian' => '19212', 'nombre' => 'Corinto'],
            ['codigo_dian' => '19256', 'nombre' => 'El Tambo'],
            ['codigo_dian' => '19290', 'nombre' => 'Florencia'],
            ['codigo_dian' => '19300', 'nombre' => 'Guachené'],
            ['codigo_dian' => '19318', 'nombre' => 'Guapi'],
            ['codigo_dian' => '19355', 'nombre' => 'Inzá'],
            ['codigo_dian' => '19364', 'nombre' => 'Jambaló'],
            ['codigo_dian' => '19392', 'nombre' => 'La Sierra'],
            ['codigo_dian' => '19397', 'nombre' => 'La Vega'],
            ['codigo_dian' => '19418', 'nombre' => 'López'],
            ['codigo_dian' => '19450', 'nombre' => 'Mercaderes'],
            ['codigo_dian' => '19455', 'nombre' => 'Miranda'],
            ['codigo_dian' => '19473', 'nombre' => 'Morales'],
            ['codigo_dian' => '19513', 'nombre' => 'Padilla'],
            ['codigo_dian' => '19517', 'nombre' => 'Paez'],
            ['codigo_dian' => '19532', 'nombre' => 'Patía'],
            ['codigo_dian' => '19533', 'nombre' => 'Piamonte'],
            ['codigo_dian' => '19548', 'nombre' => 'Piendamó'],
            ['codigo_dian' => '19573', 'nombre' => 'Puerto Tejada'],
            ['codigo_dian' => '19585', 'nombre' => 'Puracé'],
            ['codigo_dian' => '19622', 'nombre' => 'Rosas'],
            ['codigo_dian' => '19693', 'nombre' => 'San Sebastián'],
            ['codigo_dian' => '19698', 'nombre' => 'Santander De Quilichao'],
            ['codigo_dian' => '19701', 'nombre' => 'Santa Rosa'],
            ['codigo_dian' => '19743', 'nombre' => 'Silvia'],
            ['codigo_dian' => '19760', 'nombre' => 'Sotara'],
            ['codigo_dian' => '19780', 'nombre' => 'Suárez'],
            ['codigo_dian' => '19785', 'nombre' => 'Sucre'],
            ['codigo_dian' => '19807', 'nombre' => 'Timbío'],
            ['codigo_dian' => '19809', 'nombre' => 'Timbiquí'],
            ['codigo_dian' => '19821', 'nombre' => 'Toribio'],
            ['codigo_dian' => '19824', 'nombre' => 'Totoró'],
            ['codigo_dian' => '19845', 'nombre' => 'Villa Rica'],
        //CESAR
            ['codigo_dian' => '20001', 'nombre' => 'Valledupar'],
            ['codigo_dian' => '20011', 'nombre' => 'Aguachica'],
            ['codigo_dian' => '20013', 'nombre' => 'Agustín Codazzi'],
            ['codigo_dian' => '20032', 'nombre' => 'Astrea'],
            ['codigo_dian' => '20045', 'nombre' => 'Becerril'],
            ['codigo_dian' => '20060', 'nombre' => 'Bosconia'],
            ['codigo_dian' => '20175', 'nombre' => 'Chimichagua'],
            ['codigo_dian' => '20178', 'nombre' => 'Chiriguaná'],
            ['codigo_dian' => '20228', 'nombre' => 'Curumaní'],
            ['codigo_dian' => '20238', 'nombre' => 'El Copey'],
            ['codigo_dian' => '20250', 'nombre' => 'El Paso'],
            ['codigo_dian' => '20295', 'nombre' => 'Gamarra'],
            ['codigo_dian' => '20310', 'nombre' => 'González'],
            ['codigo_dian' => '20383', 'nombre' => 'La Gloria'],
            ['codigo_dian' => '20400', 'nombre' => 'La Jagua De Ibirico'],
            ['codigo_dian' => '20443', 'nombre' => 'Manaure'],
            ['codigo_dian' => '20517', 'nombre' => 'Pailitas'],
            ['codigo_dian' => '20550', 'nombre' => 'Pelaya'],
            ['codigo_dian' => '20570', 'nombre' => 'Pueblo Bello'],
            ['codigo_dian' => '20614', 'nombre' => 'Río De Oro'],
            ['codigo_dian' => '20621', 'nombre' => 'La Paz'],
            ['codigo_dian' => '20710', 'nombre' => 'San Alberto'],
            ['codigo_dian' => '20750', 'nombre' => 'San Diego'],
            ['codigo_dian' => '20770', 'nombre' => 'San Martín'],
            ['codigo_dian' => '20787', 'nombre' => 'Tamalameque'],
        //CHOCO
            ['codigo_dian' => '27001', 'nombre' => 'Quibdó'],
            ['codigo_dian' => '27006', 'nombre' => 'Acandí'],
            ['codigo_dian' => '27025', 'nombre' => 'Alto Baudó'],
            ['codigo_dian' => '27050', 'nombre' => 'Atrato'],
            ['codigo_dian' => '27073', 'nombre' => 'Bagadó'],
            ['codigo_dian' => '27075', 'nombre' => 'Bahía Solano'],
            ['codigo_dian' => '27077', 'nombre' => 'Bajo Baudó'],
            ['codigo_dian' => '27099', 'nombre' => 'Bojaya'],
            ['codigo_dian' => '27135', 'nombre' => 'El Cantón Del San Pablo'],
            ['codigo_dian' => '27150', 'nombre' => 'Carmen Del Darién'],
            ['codigo_dian' => '27160', 'nombre' => 'Cértegui'],
            ['codigo_dian' => '27205', 'nombre' => 'Condoto'],
            ['codigo_dian' => '27245', 'nombre' => 'El Carmen De Atrato'],
            ['codigo_dian' => '27250', 'nombre' => 'El Litoral Del San Juan'],
            ['codigo_dian' => '27361', 'nombre' => 'Istmina'],
            ['codigo_dian' => '27372', 'nombre' => 'Juradó'],
            ['codigo_dian' => '27413', 'nombre' => 'Lloró'],
            ['codigo_dian' => '27425', 'nombre' => 'Medio Atrato'],
            ['codigo_dian' => '27430', 'nombre' => 'Medio Baudó'],
            ['codigo_dian' => '27450', 'nombre' => 'Medio San Juan'],
            ['codigo_dian' => '27491', 'nombre' => 'Nóvita'],
            ['codigo_dian' => '27495', 'nombre' => 'Nuquí'],
            ['codigo_dian' => '27580', 'nombre' => 'Río Iró'],
            ['codigo_dian' => '27600', 'nombre' => 'Río Quito'],
            ['codigo_dian' => '27615', 'nombre' => 'Riosucio'],
            ['codigo_dian' => '27660', 'nombre' => 'San José Del Palmar'],
            ['codigo_dian' => '27745', 'nombre' => 'Sipí'],
            ['codigo_dian' => '27787', 'nombre' => 'Tadó'],
            ['codigo_dian' => '27800', 'nombre' => 'Unguía'],
            ['codigo_dian' => '27810', 'nombre' => 'Unión Panamericana'],
        //CORDOBA
            ['codigo_dian' => '23001', 'nombre' => 'Montería'],
            ['codigo_dian' => '23068', 'nombre' => 'Ayapel'],
            ['codigo_dian' => '23079', 'nombre' => 'Buenavista'],
            ['codigo_dian' => '23090', 'nombre' => 'Canalete'],
            ['codigo_dian' => '23162', 'nombre' => 'Cereté'],
            ['codigo_dian' => '23168', 'nombre' => 'Chimá'],
            ['codigo_dian' => '23182', 'nombre' => 'Chinú'],
            ['codigo_dian' => '23189', 'nombre' => 'Ciénaga De Oro'],
            ['codigo_dian' => '23300', 'nombre' => 'Cotorra'],
            ['codigo_dian' => '23350', 'nombre' => 'La Apartada'],
            ['codigo_dian' => '23417', 'nombre' => 'Lorica'],
            ['codigo_dian' => '23419', 'nombre' => 'Los Córdobas'],
            ['codigo_dian' => '23464', 'nombre' => 'Momil'],
            ['codigo_dian' => '23466', 'nombre' => 'Montelíbano'],
            ['codigo_dian' => '23500', 'nombre' => 'Moñitos'],
            ['codigo_dian' => '23555', 'nombre' => 'Planeta Rica'],
            ['codigo_dian' => '23570', 'nombre' => 'Pueblo Nuevo'],
            ['codigo_dian' => '23574', 'nombre' => 'Puerto Escondido'],
            ['codigo_dian' => '23580', 'nombre' => 'Puerto Libertador'],
            ['codigo_dian' => '23586', 'nombre' => 'Purísima'],
            ['codigo_dian' => '23660', 'nombre' => 'Sahagún'],
            ['codigo_dian' => '23670', 'nombre' => 'San Andrés Sotavento'],
            ['codigo_dian' => '23672', 'nombre' => 'San Antero'],
            ['codigo_dian' => '23675', 'nombre' => 'San Bernardo Del Viento'],
            ['codigo_dian' => '23678', 'nombre' => 'San Carlos'],
            ['codigo_dian' => '23682', 'nombre' => 'San José De Uré'],
            ['codigo_dian' => '23686', 'nombre' => 'San Pelayo'],
            ['codigo_dian' => '23807', 'nombre' => 'Tierralta'],
            ['codigo_dian' => '23815', 'nombre' => 'Tuchín'],
            ['codigo_dian' => '23855', 'nombre' => 'Valencia'],
        //CUNDINAMARCA
            ['codigo_dian' => '25001', 'nombre' => 'Agua De Dios'],
            ['codigo_dian' => '25019', 'nombre' => 'Albán'],
            ['codigo_dian' => '25035', 'nombre' => 'Anapoima'],
            ['codigo_dian' => '25040', 'nombre' => 'Anolaima'],
            ['codigo_dian' => '25053', 'nombre' => 'Arbeláez'],
            ['codigo_dian' => '25086', 'nombre' => 'Beltrán'],
            ['codigo_dian' => '25095', 'nombre' => 'Bituima'],
            ['codigo_dian' => '25099', 'nombre' => 'Bojacá'],
            ['codigo_dian' => '25120', 'nombre' => 'Cabrera'],
            ['codigo_dian' => '25123', 'nombre' => 'Cachipay'],
            ['codigo_dian' => '25126', 'nombre' => 'Cajicá'],
            ['codigo_dian' => '25148', 'nombre' => 'Caparrapí'],
            ['codigo_dian' => '25151', 'nombre' => 'Caqueza'],
            ['codigo_dian' => '25154', 'nombre' => 'Carmen De Carupa'],
            ['codigo_dian' => '25168', 'nombre' => 'Chaguaní'],
            ['codigo_dian' => '25175', 'nombre' => 'Chía'],
            ['codigo_dian' => '25178', 'nombre' => 'Chipaque'],
            ['codigo_dian' => '25181', 'nombre' => 'Choachí'],
            ['codigo_dian' => '25183', 'nombre' => 'Chocontá'],
            ['codigo_dian' => '25200', 'nombre' => 'Cogua'],
            ['codigo_dian' => '25214', 'nombre' => 'Cota'],
            ['codigo_dian' => '25224', 'nombre' => 'Cucunubá'],
            ['codigo_dian' => '25245', 'nombre' => 'El Colegio'],
            ['codigo_dian' => '25258', 'nombre' => 'El Peñón'],
            ['codigo_dian' => '25260', 'nombre' => 'El Rosal'],
            ['codigo_dian' => '25269', 'nombre' => 'Facatativá'],
            ['codigo_dian' => '25279', 'nombre' => 'Fomeque'],
            ['codigo_dian' => '25281', 'nombre' => 'Fosca'],
            ['codigo_dian' => '25286', 'nombre' => 'Funza'],
            ['codigo_dian' => '25288', 'nombre' => 'Fúquene'],
            ['codigo_dian' => '25290', 'nombre' => 'Fusagasugá'],
            ['codigo_dian' => '25293', 'nombre' => 'Gachala'],
            ['codigo_dian' => '25295', 'nombre' => 'Gachancipá'],
            ['codigo_dian' => '25297', 'nombre' => 'Gachetá'],
            ['codigo_dian' => '25299', 'nombre' => 'Gama'],
            ['codigo_dian' => '25307', 'nombre' => 'Girardot'],
            ['codigo_dian' => '25312', 'nombre' => 'Granada'],
            ['codigo_dian' => '25317', 'nombre' => 'Guachetá'],
            ['codigo_dian' => '25320', 'nombre' => 'Guaduas'],
            ['codigo_dian' => '25322', 'nombre' => 'Guasca'],
            ['codigo_dian' => '25324', 'nombre' => 'Guataquí'],
            ['codigo_dian' => '25326', 'nombre' => 'Guatavita'],
            ['codigo_dian' => '25328', 'nombre' => 'Guayabal De Siquima'],
            ['codigo_dian' => '25335', 'nombre' => 'Guayabetal'],
            ['codigo_dian' => '25339', 'nombre' => 'Gutiérrez'],
            ['codigo_dian' => '25368', 'nombre' => 'Jerusalén'],
            ['codigo_dian' => '25372', 'nombre' => 'Junín'],
            ['codigo_dian' => '25377', 'nombre' => 'La Calera'],
            ['codigo_dian' => '25386', 'nombre' => 'La Mesa'],
            ['codigo_dian' => '25394', 'nombre' => 'La Palma'],
            ['codigo_dian' => '25398', 'nombre' => 'La Peña'],
            ['codigo_dian' => '25402', 'nombre' => 'La Vega'],
            ['codigo_dian' => '25407', 'nombre' => 'Lenguazaque'],
            ['codigo_dian' => '25426', 'nombre' => 'Macheta'],
            ['codigo_dian' => '25430', 'nombre' => 'Madrid'],
            ['codigo_dian' => '25436', 'nombre' => 'Manta'],
            ['codigo_dian' => '25438', 'nombre' => 'Medina'],
            ['codigo_dian' => '25473', 'nombre' => 'Mosquera'],
            ['codigo_dian' => '25483', 'nombre' => 'Nariño'],
            ['codigo_dian' => '25486', 'nombre' => 'Nemocón'],
            ['codigo_dian' => '25488', 'nombre' => 'Nilo'],
            ['codigo_dian' => '25489', 'nombre' => 'Nimaima'],
            ['codigo_dian' => '25491', 'nombre' => 'Nocaima'],
            ['codigo_dian' => '25506', 'nombre' => 'Venecia'],
            ['codigo_dian' => '25513', 'nombre' => 'Pacho'],
            ['codigo_dian' => '25518', 'nombre' => 'Paime'],
            ['codigo_dian' => '25524', 'nombre' => 'Pandi'],
            ['codigo_dian' => '25530', 'nombre' => 'Paratebueno'],
            ['codigo_dian' => '25535', 'nombre' => 'Pasca'],
            ['codigo_dian' => '25572', 'nombre' => 'Puerto Salgar'],
            ['codigo_dian' => '25580', 'nombre' => 'Pulí'],
            ['codigo_dian' => '25592', 'nombre' => 'Quebradanegra'],
            ['codigo_dian' => '25594', 'nombre' => 'Quetame'],
            ['codigo_dian' => '25596', 'nombre' => 'Quipile'],
            ['codigo_dian' => '25599', 'nombre' => 'Apulo'],
            ['codigo_dian' => '25612', 'nombre' => 'Ricaurte'],
            ['codigo_dian' => '25645', 'nombre' => 'San Antonio Del Tequendama'],
            ['codigo_dian' => '25649', 'nombre' => 'San Bernardo'],
            ['codigo_dian' => '25653', 'nombre' => 'San Cayetano'],
            ['codigo_dian' => '25658', 'nombre' => 'San Francisco'],
            ['codigo_dian' => '25662', 'nombre' => 'San Juan De Río Seco'],
            ['codigo_dian' => '25718', 'nombre' => 'Sasaima'],
            ['codigo_dian' => '25736', 'nombre' => 'Sesquilé'],
            ['codigo_dian' => '25740', 'nombre' => 'Sibaté'],
            ['codigo_dian' => '25743', 'nombre' => 'Silvania'],
            ['codigo_dian' => '25745', 'nombre' => 'Simijaca'],
            ['codigo_dian' => '25754', 'nombre' => 'Soacha'],
            ['codigo_dian' => '25758', 'nombre' => 'Sopó'],
            ['codigo_dian' => '25769', 'nombre' => 'Subachoque'],
            ['codigo_dian' => '25772', 'nombre' => 'Suesca'],
            ['codigo_dian' => '25777', 'nombre' => 'Supatá'],
            ['codigo_dian' => '25779', 'nombre' => 'Susa'],
            ['codigo_dian' => '25781', 'nombre' => 'Sutatausa'],
            ['codigo_dian' => '25785', 'nombre' => 'Tabio'],
            ['codigo_dian' => '25793', 'nombre' => 'Tausa'],
            ['codigo_dian' => '25797', 'nombre' => 'Tena'],
            ['codigo_dian' => '25799', 'nombre' => 'Tenjo'],
            ['codigo_dian' => '25805', 'nombre' => 'Tibacuy'],
            ['codigo_dian' => '25807', 'nombre' => 'Tibirita'],
            ['codigo_dian' => '25815', 'nombre' => 'Tocaima'],
            ['codigo_dian' => '25817', 'nombre' => 'Tocancipá'],
            ['codigo_dian' => '25823', 'nombre' => 'Topaipí'],
            ['codigo_dian' => '25839', 'nombre' => 'Ubalá'],
            ['codigo_dian' => '25841', 'nombre' => 'Ubaque'],
            ['codigo_dian' => '25843', 'nombre' => 'Villa De San Diego De Ubate'],
            ['codigo_dian' => '25845', 'nombre' => 'Une'],
            ['codigo_dian' => '25851', 'nombre' => 'Útica'],
            ['codigo_dian' => '25862', 'nombre' => 'Vergara'],
            ['codigo_dian' => '25867', 'nombre' => 'Vianí'],
            ['codigo_dian' => '25871', 'nombre' => 'Villagómez'],
            ['codigo_dian' => '25873', 'nombre' => 'Villapinzón'],
            ['codigo_dian' => '25875', 'nombre' => 'Villeta'],
            ['codigo_dian' => '25878', 'nombre' => 'Viotá'],
            ['codigo_dian' => '25885', 'nombre' => 'Yacopí'],
            ['codigo_dian' => '25898', 'nombre' => 'Zipacón'],
            ['codigo_dian' => '25899', 'nombre' => 'Zipaquirá'],
        //GUAINIA
            ['codigo_dian' => '94001', 'nombre' => 'Inírida'],
            ['codigo_dian' => '94343', 'nombre' => 'Barranco Minas'],
            ['codigo_dian' => '94663', 'nombre' => 'Mapiripana'],
            ['codigo_dian' => '94883', 'nombre' => 'San Felipe'],
            ['codigo_dian' => '94884', 'nombre' => 'Puerto Colombia'],
            ['codigo_dian' => '94885', 'nombre' => 'La Guadalupe'],
            ['codigo_dian' => '94886', 'nombre' => 'Cacahual'],
            ['codigo_dian' => '94887', 'nombre' => 'Pana Pana'],
            ['codigo_dian' => '94888', 'nombre' => 'Morichal'],
        //GUAVIARE
            ['codigo_dian' => '95001', 'nombre' => 'San José Del Guaviare'],
            ['codigo_dian' => '95015', 'nombre' => 'Calamar'],
            ['codigo_dian' => '95025', 'nombre' => 'El Retorno'],
            ['codigo_dian' => '95200', 'nombre' => 'Miraflores'],
        //HUILA
            ['codigo_dian' => '41001', 'nombre' => 'Neiva'],
            ['codigo_dian' => '41006', 'nombre' => 'Acevedo'],
            ['codigo_dian' => '41013', 'nombre' => 'Agrado'],
            ['codigo_dian' => '41016', 'nombre' => 'Aipe'],
            ['codigo_dian' => '41020', 'nombre' => 'Algeciras'],
            ['codigo_dian' => '41026', 'nombre' => 'Altamira'],
            ['codigo_dian' => '41078', 'nombre' => 'Baraya'],
            ['codigo_dian' => '41132', 'nombre' => 'Campoalegre'],
            ['codigo_dian' => '41206', 'nombre' => 'Colombia'],
            ['codigo_dian' => '41244', 'nombre' => 'Elías'],
            ['codigo_dian' => '41298', 'nombre' => 'Garzón'],
            ['codigo_dian' => '41306', 'nombre' => 'Gigante'],
            ['codigo_dian' => '41319', 'nombre' => 'Guadalupe'],
            ['codigo_dian' => '41349', 'nombre' => 'Hobo'],
            ['codigo_dian' => '41357', 'nombre' => 'Iquira'],
            ['codigo_dian' => '41359', 'nombre' => 'Isnos'],
            ['codigo_dian' => '41378', 'nombre' => 'La Argentina'],
            ['codigo_dian' => '41396', 'nombre' => 'La Plata'],
            ['codigo_dian' => '41483', 'nombre' => 'Nátaga'],
            ['codigo_dian' => '41503', 'nombre' => 'Oporapa'],
            ['codigo_dian' => '41518', 'nombre' => 'Paicol'],
            ['codigo_dian' => '41524', 'nombre' => 'Palermo'],
            ['codigo_dian' => '41530', 'nombre' => 'Palestina'],
            ['codigo_dian' => '41548', 'nombre' => 'Pital'],
            ['codigo_dian' => '41551', 'nombre' => 'Pitalito'],
            ['codigo_dian' => '41615', 'nombre' => 'Rivera'],
            ['codigo_dian' => '41660', 'nombre' => 'Saladoblanco'],
            ['codigo_dian' => '41668', 'nombre' => 'San Agustín'],
            ['codigo_dian' => '41676', 'nombre' => 'Santa María'],
            ['codigo_dian' => '41770', 'nombre' => 'Suaza'],
            ['codigo_dian' => '41791', 'nombre' => 'Tarqui'],
            ['codigo_dian' => '41797', 'nombre' => 'Tesalia'],
            ['codigo_dian' => '41799', 'nombre' => 'Tello'],
            ['codigo_dian' => '41801', 'nombre' => 'Teruel'],
            ['codigo_dian' => '41807', 'nombre' => 'Timaná'],
            ['codigo_dian' => '41872', 'nombre' => 'Villavieja'],
            ['codigo_dian' => '41885', 'nombre' => 'Yaguará'],
        //GUAJIRA
            ['codigo_dian' => '44001', 'nombre' => 'Riohacha'],
            ['codigo_dian' => '44035', 'nombre' => 'Albania'],
            ['codigo_dian' => '44078', 'nombre' => 'Barrancas'],
            ['codigo_dian' => '44090', 'nombre' => 'Dibulla'],
            ['codigo_dian' => '44098', 'nombre' => 'Distracción'],
            ['codigo_dian' => '44110', 'nombre' => 'El Molino'],
            ['codigo_dian' => '44279', 'nombre' => 'Fonseca'],
            ['codigo_dian' => '44378', 'nombre' => 'Hatonuevo'],
            ['codigo_dian' => '44420', 'nombre' => 'La Jagua Del Pilar'],
            ['codigo_dian' => '44430', 'nombre' => 'Maicao'],
            ['codigo_dian' => '44560', 'nombre' => 'Manaure'],
            ['codigo_dian' => '44650', 'nombre' => 'San Juan Del Cesar'],
            ['codigo_dian' => '44847', 'nombre' => 'Uribia'],
            ['codigo_dian' => '44855', 'nombre' => 'Urumita'],
            ['codigo_dian' => '44874', 'nombre' => 'Villanueva'],
        //MAGDALENA
            ['codigo_dian' => '47001', 'nombre' => 'Santa Marta'],
            ['codigo_dian' => '47030', 'nombre' => 'Algarrobo'],
            ['codigo_dian' => '47053', 'nombre' => 'Aracataca'],
            ['codigo_dian' => '47058', 'nombre' => 'Ariguaní'],
            ['codigo_dian' => '47161', 'nombre' => 'Cerro San Antonio'],
            ['codigo_dian' => '47170', 'nombre' => 'Chivolo'],
            ['codigo_dian' => '47189', 'nombre' => 'Ciénaga'],
            ['codigo_dian' => '47205', 'nombre' => 'Concordia'],
            ['codigo_dian' => '47245', 'nombre' => 'El Banco'],
            ['codigo_dian' => '47258', 'nombre' => 'El Piñon'],
            ['codigo_dian' => '47268', 'nombre' => 'El Retén'],
            ['codigo_dian' => '47288', 'nombre' => 'Fundación'],
            ['codigo_dian' => '47318', 'nombre' => 'Guamal'],
            ['codigo_dian' => '47460', 'nombre' => 'Nueva Granada'],
            ['codigo_dian' => '47541', 'nombre' => 'Pedraza'],
            ['codigo_dian' => '47545', 'nombre' => 'Pijiño Del Carmen'],
            ['codigo_dian' => '47551', 'nombre' => 'Pivijay'],
            ['codigo_dian' => '47555', 'nombre' => 'Plato'],
            ['codigo_dian' => '47570', 'nombre' => 'Puebloviejo'],
            ['codigo_dian' => '47605', 'nombre' => 'Remolino'],
            ['codigo_dian' => '47660', 'nombre' => 'Sabanas De San Angel'],
            ['codigo_dian' => '47675', 'nombre' => 'Salamina'],
            ['codigo_dian' => '47692', 'nombre' => 'San Sebastián De Buenavista'],
            ['codigo_dian' => '47703', 'nombre' => 'San Zenón'],
            ['codigo_dian' => '47707', 'nombre' => 'Santa Ana'],
            ['codigo_dian' => '47720', 'nombre' => 'Santa Bárbara De Pinto'],
            ['codigo_dian' => '47745', 'nombre' => 'Sitionuevo'],
            ['codigo_dian' => '47798', 'nombre' => 'Tenerife'],
            ['codigo_dian' => '47960', 'nombre' => 'Zapayán'],
            ['codigo_dian' => '47980', 'nombre' => 'Zona Bananera'],
        //META
            ['codigo_dian' => '50001', 'nombre' => 'Villavicencio'],
            ['codigo_dian' => '50006', 'nombre' => 'Acacías'],
            ['codigo_dian' => '50110', 'nombre' => 'Barranca De Upía'],
            ['codigo_dian' => '50124', 'nombre' => 'Cabuyaro'],
            ['codigo_dian' => '50150', 'nombre' => 'Castilla La Nueva'],
            ['codigo_dian' => '50223', 'nombre' => 'Cubarral'],
            ['codigo_dian' => '50226', 'nombre' => 'Cumaral'],
            ['codigo_dian' => '50245', 'nombre' => 'El Calvario'],
            ['codigo_dian' => '50251', 'nombre' => 'El Castillo'],
            ['codigo_dian' => '50270', 'nombre' => 'El Dorado'],
            ['codigo_dian' => '50287', 'nombre' => 'Fuente De Oro'],
            ['codigo_dian' => '50313', 'nombre' => 'Granada'],
            ['codigo_dian' => '50318', 'nombre' => 'Guamal'],
            ['codigo_dian' => '50325', 'nombre' => 'Mapiripán'],
            ['codigo_dian' => '50330', 'nombre' => 'Mesetas'],
            ['codigo_dian' => '50350', 'nombre' => 'La Macarena'],
            ['codigo_dian' => '50370', 'nombre' => 'Uribe'],
            ['codigo_dian' => '50400', 'nombre' => 'Lejanías'],
            ['codigo_dian' => '50450', 'nombre' => 'Puerto Concordia'],
            ['codigo_dian' => '50568', 'nombre' => 'Puerto Gaitán'],
            ['codigo_dian' => '50573', 'nombre' => 'Puerto López'],
            ['codigo_dian' => '50577', 'nombre' => 'Puerto Lleras'],
            ['codigo_dian' => '50590', 'nombre' => 'Puerto Rico'],
            ['codigo_dian' => '50606', 'nombre' => 'Restrepo'],
            ['codigo_dian' => '50680', 'nombre' => 'San Carlos De Guaroa'],
            ['codigo_dian' => '50683', 'nombre' => 'San Juan De Arama'],
            ['codigo_dian' => '50686', 'nombre' => 'San Juanito'],
            ['codigo_dian' => '50689', 'nombre' => 'San Martín'],
            ['codigo_dian' => '50711', 'nombre' => 'Vistahermosa'],
        //NARIÑO
            ['codigo_dian' => '52001', 'nombre' => 'Pasto'],
            ['codigo_dian' => '52019', 'nombre' => 'Albán'],
            ['codigo_dian' => '52022', 'nombre' => 'Aldana'],
            ['codigo_dian' => '52036', 'nombre' => 'Ancuyá'],
            ['codigo_dian' => '52051', 'nombre' => 'Arboleda'],
            ['codigo_dian' => '52079', 'nombre' => 'Barbacoas'],
            ['codigo_dian' => '52083', 'nombre' => 'Belén'],
            ['codigo_dian' => '52110', 'nombre' => 'Buesaco'],
            ['codigo_dian' => '52203', 'nombre' => 'Colón'],
            ['codigo_dian' => '52207', 'nombre' => 'Consaca'],
            ['codigo_dian' => '52210', 'nombre' => 'Contadero'],
            ['codigo_dian' => '52215', 'nombre' => 'Córdoba'],
            ['codigo_dian' => '52224', 'nombre' => 'Cuaspud'],
            ['codigo_dian' => '52227', 'nombre' => 'Cumbal'],
            ['codigo_dian' => '52233', 'nombre' => 'Cumbitara'],
            ['codigo_dian' => '52240', 'nombre' => 'Chachagüí'],
            ['codigo_dian' => '52250', 'nombre' => 'El Charco'],
            ['codigo_dian' => '52254', 'nombre' => 'El Peñol'],
            ['codigo_dian' => '52256', 'nombre' => 'El Rosario'],
            ['codigo_dian' => '52258', 'nombre' => 'El Tablón De Gómez'],
            ['codigo_dian' => '52260', 'nombre' => 'El Tambo'],
            ['codigo_dian' => '52287', 'nombre' => 'Funes'],
            ['codigo_dian' => '52317', 'nombre' => 'Guachucal'],
            ['codigo_dian' => '52320', 'nombre' => 'Guaitarilla'],
            ['codigo_dian' => '52323', 'nombre' => 'Gualmatán'],
            ['codigo_dian' => '52352', 'nombre' => 'Iles'],
            ['codigo_dian' => '52354', 'nombre' => 'Imués'],
            ['codigo_dian' => '52356', 'nombre' => 'Ipiales'],
            ['codigo_dian' => '52378', 'nombre' => 'La Cruz'],
            ['codigo_dian' => '52381', 'nombre' => 'La Florida'],
            ['codigo_dian' => '52385', 'nombre' => 'La Llanada'],
            ['codigo_dian' => '52390', 'nombre' => 'La Tola'],
            ['codigo_dian' => '52399', 'nombre' => 'La Unión'],
            ['codigo_dian' => '52405', 'nombre' => 'Leiva'],
            ['codigo_dian' => '52411', 'nombre' => 'Linares'],
            ['codigo_dian' => '52418', 'nombre' => 'Los Andes'],
            ['codigo_dian' => '52427', 'nombre' => 'Magüi'],
            ['codigo_dian' => '52435', 'nombre' => 'Mallama'],
            ['codigo_dian' => '52473', 'nombre' => 'Mosquera'],
            ['codigo_dian' => '52480', 'nombre' => 'Nariño'],
            ['codigo_dian' => '52490', 'nombre' => 'Olaya Herrera'],
            ['codigo_dian' => '52506', 'nombre' => 'Ospina'],
            ['codigo_dian' => '52520', 'nombre' => 'Francisco Pizarro'],
            ['codigo_dian' => '52540', 'nombre' => 'Policarpa'],
            ['codigo_dian' => '52560', 'nombre' => 'Potosí'],
            ['codigo_dian' => '52565', 'nombre' => 'Providencia'],
            ['codigo_dian' => '52573', 'nombre' => 'Puerres'],
            ['codigo_dian' => '52585', 'nombre' => 'Pupiales'],
            ['codigo_dian' => '52612', 'nombre' => 'Ricaurte'],
            ['codigo_dian' => '52621', 'nombre' => 'Roberto Payán'],
            ['codigo_dian' => '52678', 'nombre' => 'Samaniego'],
            ['codigo_dian' => '52683', 'nombre' => 'Sandoná'],
            ['codigo_dian' => '52685', 'nombre' => 'San Bernardo'],
            ['codigo_dian' => '52687', 'nombre' => 'San Lorenzo'],
            ['codigo_dian' => '52693', 'nombre' => 'San Pablo'],
            ['codigo_dian' => '52694', 'nombre' => 'San Pedro De Cartago'],
            ['codigo_dian' => '52696', 'nombre' => 'Santa Bárbara'],
            ['codigo_dian' => '52699', 'nombre' => 'Santacruz'],
            ['codigo_dian' => '52720', 'nombre' => 'Sapuyes'],
            ['codigo_dian' => '52786', 'nombre' => 'Taminango'],
            ['codigo_dian' => '52788', 'nombre' => 'Tangua'],
            ['codigo_dian' => '52835', 'nombre' => 'San Andres De Tumaco'],
            ['codigo_dian' => '52838', 'nombre' => 'Túquerres'],
            ['codigo_dian' => '52885', 'nombre' => 'Yacuanquer'],
        //N. SANTANDER
            ['codigo_dian' => '54001', 'nombre' => 'Cúcuta'],
            ['codigo_dian' => '54003', 'nombre' => 'Abrego'],
            ['codigo_dian' => '54051', 'nombre' => 'Arboledas'],
            ['codigo_dian' => '54099', 'nombre' => 'Bochalema'],
            ['codigo_dian' => '54109', 'nombre' => 'Bucarasica'],
            ['codigo_dian' => '54125', 'nombre' => 'Cácota'],
            ['codigo_dian' => '54128', 'nombre' => 'Cachirá'],
            ['codigo_dian' => '54172', 'nombre' => 'Chinácota'],
            ['codigo_dian' => '54174', 'nombre' => 'Chitagá'],
            ['codigo_dian' => '54206', 'nombre' => 'Convención'],
            ['codigo_dian' => '54223', 'nombre' => 'Cucutilla'],
            ['codigo_dian' => '54239', 'nombre' => 'Durania'],
            ['codigo_dian' => '54245', 'nombre' => 'El Carmen'],
            ['codigo_dian' => '54250', 'nombre' => 'El Tarra'],
            ['codigo_dian' => '54261', 'nombre' => 'El Zulia'],
            ['codigo_dian' => '54313', 'nombre' => 'Gramalote'],
            ['codigo_dian' => '54344', 'nombre' => 'Hacarí'],
            ['codigo_dian' => '54347', 'nombre' => 'Herrán'],
            ['codigo_dian' => '54377', 'nombre' => 'Labateca'],
            ['codigo_dian' => '54385', 'nombre' => 'La Esperanza'],
            ['codigo_dian' => '54398', 'nombre' => 'La Playa'],
            ['codigo_dian' => '54405', 'nombre' => 'Los Patios'],
            ['codigo_dian' => '54418', 'nombre' => 'Lourdes'],
            ['codigo_dian' => '54480', 'nombre' => 'Mutiscua'],
            ['codigo_dian' => '54498', 'nombre' => 'Ocaña'],
            ['codigo_dian' => '54518', 'nombre' => 'Pamplona'],
            ['codigo_dian' => '54520', 'nombre' => 'Pamplonita'],
            ['codigo_dian' => '54553', 'nombre' => 'Puerto Santander'],
            ['codigo_dian' => '54599', 'nombre' => 'Ragonvalia'],
            ['codigo_dian' => '54660', 'nombre' => 'Salazar'],
            ['codigo_dian' => '54670', 'nombre' => 'San Calixto'],
            ['codigo_dian' => '54673', 'nombre' => 'San Cayetano'],
            ['codigo_dian' => '54680', 'nombre' => 'Santiago'],
            ['codigo_dian' => '54720', 'nombre' => 'Sardinata'],
            ['codigo_dian' => '54743', 'nombre' => 'Silos'],
            ['codigo_dian' => '54800', 'nombre' => 'Teorama'],
            ['codigo_dian' => '54810', 'nombre' => 'Tibú'],
            ['codigo_dian' => '54820', 'nombre' => 'Toledo'],
            ['codigo_dian' => '54871', 'nombre' => 'Villa Caro'],
            ['codigo_dian' => '54874', 'nombre' => 'Villa Del Rosario'],
        //PUTUMAYO
            ['codigo_dian' => '86001', 'nombre' => 'Mocoa'],
            ['codigo_dian' => '86219', 'nombre' => 'Colón'],
            ['codigo_dian' => '86320', 'nombre' => 'Orito'],
            ['codigo_dian' => '86568', 'nombre' => 'Puerto Asís'],
            ['codigo_dian' => '86569', 'nombre' => 'Puerto Caicedo'],
            ['codigo_dian' => '86571', 'nombre' => 'Puerto Guzmán'],
            ['codigo_dian' => '86573', 'nombre' => 'Puerto Leguízamo'],
            ['codigo_dian' => '86749', 'nombre' => 'Sibundoy'],
            ['codigo_dian' => '86755', 'nombre' => 'San Francisco'],
            ['codigo_dian' => '86757', 'nombre' => 'San Miguel'],
            ['codigo_dian' => '86760', 'nombre' => 'Santiago'],
            ['codigo_dian' => '86865', 'nombre' => 'Valle Del Guamuez'],
            ['codigo_dian' => '86885', 'nombre' => 'Villagarzón'],
        //QUINDIO
            ['codigo_dian' => '63001', 'nombre' => 'Armenia'],
            ['codigo_dian' => '63111', 'nombre' => 'Buenavista'],
            ['codigo_dian' => '63130', 'nombre' => 'Calarca'],
            ['codigo_dian' => '63190', 'nombre' => 'Circasia'],
            ['codigo_dian' => '63212', 'nombre' => 'Córdoba'],
            ['codigo_dian' => '63272', 'nombre' => 'Filandia'],
            ['codigo_dian' => '63302', 'nombre' => 'Génova'],
            ['codigo_dian' => '63401', 'nombre' => 'La Tebaida'],
            ['codigo_dian' => '63470', 'nombre' => 'Montenegro'],
            ['codigo_dian' => '63548', 'nombre' => 'Pijao'],
            ['codigo_dian' => '63594', 'nombre' => 'Quimbaya'],
            ['codigo_dian' => '63690', 'nombre' => 'Salento'],
        //RISARALDA
            ['codigo_dian' => '66001', 'nombre' => 'Pereira'],
            ['codigo_dian' => '66045', 'nombre' => 'Apía'],
            ['codigo_dian' => '66075', 'nombre' => 'Balboa'],
            ['codigo_dian' => '66088', 'nombre' => 'Belén De Umbría'],
            ['codigo_dian' => '66170', 'nombre' => 'Dosquebradas'],
            ['codigo_dian' => '66318', 'nombre' => 'Guática'],
            ['codigo_dian' => '66383', 'nombre' => 'La Celia'],
            ['codigo_dian' => '66400', 'nombre' => 'La Virginia'],
            ['codigo_dian' => '66440', 'nombre' => 'Marsella'],
            ['codigo_dian' => '66456', 'nombre' => 'Mistrató'],
            ['codigo_dian' => '66572', 'nombre' => 'Pueblo Rico'],
            ['codigo_dian' => '66594', 'nombre' => 'Quinchía'],
            ['codigo_dian' => '66682', 'nombre' => 'Santa Rosa De Cabal'],
            ['codigo_dian' => '66687', 'nombre' => 'Santuario'],
        //SAN ANDRES Y PROVIDENCIA
            ['codigo_dian' => '88001', 'nombre' => 'San Andrés'],
            ['codigo_dian' => '88564', 'nombre' => 'Providencia'],
        //SANTANDER
            ['codigo_dian' => '68001', 'nombre' => 'Bucaramanga'],
            ['codigo_dian' => '68013', 'nombre' => 'Aguada'],
            ['codigo_dian' => '68020', 'nombre' => 'Albania'],
            ['codigo_dian' => '68051', 'nombre' => 'Aratoca'],
            ['codigo_dian' => '68077', 'nombre' => 'Barbosa'],
            ['codigo_dian' => '68079', 'nombre' => 'Barichara'],
            ['codigo_dian' => '68081', 'nombre' => 'Barrancabermeja'],
            ['codigo_dian' => '68092', 'nombre' => 'Betulia'],
            ['codigo_dian' => '68101', 'nombre' => 'Bolívar'],
            ['codigo_dian' => '68121', 'nombre' => 'Cabrera'],
            ['codigo_dian' => '68132', 'nombre' => 'California'],
            ['codigo_dian' => '68147', 'nombre' => 'Capitanejo'],
            ['codigo_dian' => '68152', 'nombre' => 'Carcasí'],
            ['codigo_dian' => '68160', 'nombre' => 'Cepitá'],
            ['codigo_dian' => '68162', 'nombre' => 'Cerrito'],
            ['codigo_dian' => '68167', 'nombre' => 'Charalá'],
            ['codigo_dian' => '68169', 'nombre' => 'Charta'],
            ['codigo_dian' => '68176', 'nombre' => 'Chima'],
            ['codigo_dian' => '68179', 'nombre' => 'Chipatá'],
            ['codigo_dian' => '68190', 'nombre' => 'Cimitarra'],
            ['codigo_dian' => '68207', 'nombre' => 'Concepción'],
            ['codigo_dian' => '68209', 'nombre' => 'Confines'],
            ['codigo_dian' => '68211', 'nombre' => 'Contratación'],
            ['codigo_dian' => '68217', 'nombre' => 'Coromoro'],
            ['codigo_dian' => '68229', 'nombre' => 'Curití'],
            ['codigo_dian' => '68235', 'nombre' => 'El Carmen De Chucurí'],
            ['codigo_dian' => '68245', 'nombre' => 'El Guacamayo'],
            ['codigo_dian' => '68250', 'nombre' => 'El Peñón'],
            ['codigo_dian' => '68255', 'nombre' => 'El Playón'],
            ['codigo_dian' => '68264', 'nombre' => 'Encino'],
            ['codigo_dian' => '68266', 'nombre' => 'Enciso'],
            ['codigo_dian' => '68271', 'nombre' => 'Florián'],
            ['codigo_dian' => '68276', 'nombre' => 'Floridablanca'],
            ['codigo_dian' => '68296', 'nombre' => 'Galán'],
            ['codigo_dian' => '68298', 'nombre' => 'Gambita'],
            ['codigo_dian' => '68307', 'nombre' => 'Girón'],
            ['codigo_dian' => '68318', 'nombre' => 'Guaca'],
            ['codigo_dian' => '68320', 'nombre' => 'Guadalupe'],
            ['codigo_dian' => '68322', 'nombre' => 'Guapotá'],
            ['codigo_dian' => '68324', 'nombre' => 'Guavatá'],
            ['codigo_dian' => '68327', 'nombre' => 'Güepsa'],
            ['codigo_dian' => '68344', 'nombre' => 'Hato'],
            ['codigo_dian' => '68368', 'nombre' => 'Jesús María'],
            ['codigo_dian' => '68370', 'nombre' => 'Jordán'],
            ['codigo_dian' => '68377', 'nombre' => 'La Belleza'],
            ['codigo_dian' => '68385', 'nombre' => 'Landázuri'],
            ['codigo_dian' => '68397', 'nombre' => 'La Paz'],
            ['codigo_dian' => '68406', 'nombre' => 'Lebrija'],
            ['codigo_dian' => '68418', 'nombre' => 'Los Santos'],
            ['codigo_dian' => '68425', 'nombre' => 'Macaravita'],
            ['codigo_dian' => '68432', 'nombre' => 'Málaga'],
            ['codigo_dian' => '68444', 'nombre' => 'Matanza'],
            ['codigo_dian' => '68464', 'nombre' => 'Mogotes'],
            ['codigo_dian' => '68468', 'nombre' => 'Molagavita'],
            ['codigo_dian' => '68498', 'nombre' => 'Ocamonte'],
            ['codigo_dian' => '68500', 'nombre' => 'Oiba'],
            ['codigo_dian' => '68502', 'nombre' => 'Onzaga'],
            ['codigo_dian' => '68522', 'nombre' => 'Palmar'],
            ['codigo_dian' => '68524', 'nombre' => 'Palmas Del Socorro'],
            ['codigo_dian' => '68533', 'nombre' => 'Páramo'],
            ['codigo_dian' => '68547', 'nombre' => 'Piedecuesta'],
            ['codigo_dian' => '68549', 'nombre' => 'Pinchote'],
            ['codigo_dian' => '68572', 'nombre' => 'Puente Nacional'],
            ['codigo_dian' => '68573', 'nombre' => 'Puerto Parra'],
            ['codigo_dian' => '68575', 'nombre' => 'Puerto Wilches'],
            ['codigo_dian' => '68615', 'nombre' => 'Rionegro'],
            ['codigo_dian' => '68655', 'nombre' => 'Sabana De Torres'],
            ['codigo_dian' => '68669', 'nombre' => 'San Andrés'],
            ['codigo_dian' => '68673', 'nombre' => 'San Benito'],
            ['codigo_dian' => '68679', 'nombre' => 'San Gil'],
            ['codigo_dian' => '68682', 'nombre' => 'San Joaquín'],
            ['codigo_dian' => '68684', 'nombre' => 'San José De Miranda'],
            ['codigo_dian' => '68686', 'nombre' => 'San Miguel'],
            ['codigo_dian' => '68689', 'nombre' => 'San Vicente De Chucurí'],
            ['codigo_dian' => '68705', 'nombre' => 'Santa Bárbara'],
            ['codigo_dian' => '68720', 'nombre' => 'Santa Helena Del Opón'],
            ['codigo_dian' => '68745', 'nombre' => 'Simacota'],
            ['codigo_dian' => '68755', 'nombre' => 'Socorro'],
            ['codigo_dian' => '68770', 'nombre' => 'Suaita'],
            ['codigo_dian' => '68773', 'nombre' => 'Sucre'],
            ['codigo_dian' => '68780', 'nombre' => 'Suratá'],
            ['codigo_dian' => '68820', 'nombre' => 'Tona'],
            ['codigo_dian' => '68855', 'nombre' => 'Valle De San José'],
            ['codigo_dian' => '68861', 'nombre' => 'Vélez'],
            ['codigo_dian' => '68867', 'nombre' => 'Vetas'],
            ['codigo_dian' => '68872', 'nombre' => 'Villanueva'],
            ['codigo_dian' => '68895', 'nombre' => 'Zapatoca'],
        // Sucre
            ['codigo_dian' => '70001', 'nombre' => 'Sincelejo'],
            ['codigo_dian' => '70110', 'nombre' => 'Buenavista'],
            ['codigo_dian' => '70124', 'nombre' => 'Caimito'],
            ['codigo_dian' => '70204', 'nombre' => 'Coloso'],
            ['codigo_dian' => '70215', 'nombre' => 'Corozal'],
            ['codigo_dian' => '70221', 'nombre' => 'Coveñas'],
            ['codigo_dian' => '70230', 'nombre' => 'Chalán'],
            ['codigo_dian' => '70233', 'nombre' => 'El Roble'],
            ['codigo_dian' => '70235', 'nombre' => 'Galeras'],
            ['codigo_dian' => '70265', 'nombre' => 'Guaranda'],
            ['codigo_dian' => '70400', 'nombre' => 'La Unión'],
            ['codigo_dian' => '70418', 'nombre' => 'Los Palmitos'],
            ['codigo_dian' => '70429', 'nombre' => 'Majagual'],
            ['codigo_dian' => '70473', 'nombre' => 'Morroa'],
            ['codigo_dian' => '70508', 'nombre' => 'Ovejas'],
            ['codigo_dian' => '70523', 'nombre' => 'Palmito'],
            ['codigo_dian' => '70670', 'nombre' => 'Sampués'],
            ['codigo_dian' => '70678', 'nombre' => 'San Benito Abad'],
            ['codigo_dian' => '70702', 'nombre' => 'San Juan De Betulia'],
            ['codigo_dian' => '70708', 'nombre' => 'San Marcos'],
            ['codigo_dian' => '70713', 'nombre' => 'San Onofre'],
            ['codigo_dian' => '70717', 'nombre' => 'San Pedro'],
            ['codigo_dian' => '70742', 'nombre' => 'San Luis De Sincé'],
            ['codigo_dian' => '70771', 'nombre' => 'Sucre'],
            ['codigo_dian' => '70820', 'nombre' => 'Santiago De Tolú'],
            ['codigo_dian' => '70823', 'nombre' => 'Tolú Viejo'],
        // Tolima
            ['codigo_dian' => '73001', 'nombre' => 'Ibagué'],
            ['codigo_dian' => '73024', 'nombre' => 'Alpujarra'],
            ['codigo_dian' => '73026', 'nombre' => 'Alvarado'],
            ['codigo_dian' => '73030', 'nombre' => 'Ambalema'],
            ['codigo_dian' => '73043', 'nombre' => 'Anzoátegui'],
            ['codigo_dian' => '73055', 'nombre' => 'Armero'],
            ['codigo_dian' => '73067', 'nombre' => 'Ataco'],
            ['codigo_dian' => '73124', 'nombre' => 'Cajamarca'],
            ['codigo_dian' => '73148', 'nombre' => 'Carmen De Apicalá'],
            ['codigo_dian' => '73152', 'nombre' => 'Casabianca'],
            ['codigo_dian' => '73168', 'nombre' => 'Chaparral'],
            ['codigo_dian' => '73200', 'nombre' => 'Coello'],
            ['codigo_dian' => '73217', 'nombre' => 'Coyaima'],
            ['codigo_dian' => '73226', 'nombre' => 'Cunday'],
            ['codigo_dian' => '73236', 'nombre' => 'Dolores'],
            ['codigo_dian' => '73268', 'nombre' => 'Espinal'],
            ['codigo_dian' => '73270', 'nombre' => 'Falan'],
            ['codigo_dian' => '73275', 'nombre' => 'Flandes'],
            ['codigo_dian' => '73283', 'nombre' => 'Fresno'],
            ['codigo_dian' => '73319', 'nombre' => 'Guamo'],
            ['codigo_dian' => '73347', 'nombre' => 'Herveo'],
            ['codigo_dian' => '73349', 'nombre' => 'Honda'],
            ['codigo_dian' => '73352', 'nombre' => 'Icononzo'],
            ['codigo_dian' => '73408', 'nombre' => 'Lérida'],
            ['codigo_dian' => '73411', 'nombre' => 'Líbano'],
            ['codigo_dian' => '73443', 'nombre' => 'San Sebastián De Mariquita'],
            ['codigo_dian' => '73449', 'nombre' => 'Melgar'],
            ['codigo_dian' => '73461', 'nombre' => 'Murillo'],
            ['codigo_dian' => '73483', 'nombre' => 'Natagaima'],
            ['codigo_dian' => '73504', 'nombre' => 'Ortega'],
            ['codigo_dian' => '73520', 'nombre' => 'Palocabildo'],
            ['codigo_dian' => '73547', 'nombre' => 'Piedras'],
            ['codigo_dian' => '73555', 'nombre' => 'Planadas'],
            ['codigo_dian' => '73563', 'nombre' => 'Prado'],
            ['codigo_dian' => '73585', 'nombre' => 'Purificación'],
            ['codigo_dian' => '73616', 'nombre' => 'Rioblanco'],
            ['codigo_dian' => '73622', 'nombre' => 'Roncesvalles'],
            ['codigo_dian' => '73624', 'nombre' => 'Rovira'],
            ['codigo_dian' => '73671', 'nombre' => 'Saldaña'],
            ['codigo_dian' => '73675', 'nombre' => 'San Antonio'],
            ['codigo_dian' => '73678', 'nombre' => 'San Luis'],
            ['codigo_dian' => '73686', 'nombre' => 'Santa Isabel'],
            ['codigo_dian' => '73770', 'nombre' => 'Suárez'],
            ['codigo_dian' => '73854', 'nombre' => 'Valle De San Juan'],
            ['codigo_dian' => '73861', 'nombre' => 'Venadillo'],
            ['codigo_dian' => '73870', 'nombre' => 'Villahermosa'],
            ['codigo_dian' => '73873', 'nombre' => 'Villarrica'],
        // Valle del Cauca
            ['codigo_dian' => '76001', 'nombre' => 'Cali'],
            ['codigo_dian' => '76020', 'nombre' => 'Alcalá'],
            ['codigo_dian' => '76036', 'nombre' => 'Andalucía'],
            ['codigo_dian' => '76041', 'nombre' => 'Ansermanuevo'],
            ['codigo_dian' => '76054', 'nombre' => 'Argelia'],
            ['codigo_dian' => '76100', 'nombre' => 'Bolívar'],
            ['codigo_dian' => '76109', 'nombre' => 'Buenaventura'],
            ['codigo_dian' => '76111', 'nombre' => 'Guadalajara De Buga'],
            ['codigo_dian' => '76113', 'nombre' => 'Bugalagrande'],
            ['codigo_dian' => '76122', 'nombre' => 'Caicedonia'],
            ['codigo_dian' => '76126', 'nombre' => 'Calima'],
            ['codigo_dian' => '76130', 'nombre' => 'Candelaria'],
            ['codigo_dian' => '76147', 'nombre' => 'Cartago'],
            ['codigo_dian' => '76233', 'nombre' => 'Dagua'],
            ['codigo_dian' => '76243', 'nombre' => 'El Águila'],
            ['codigo_dian' => '76246', 'nombre' => 'El Cairo'],
            ['codigo_dian' => '76248', 'nombre' => 'El Cerrito'],
            ['codigo_dian' => '76250', 'nombre' => 'El Dovio'],
            ['codigo_dian' => '76275', 'nombre' => 'Florida'],
            ['codigo_dian' => '76306', 'nombre' => 'Ginebra'],
            ['codigo_dian' => '76318', 'nombre' => 'Guacarí'],
            ['codigo_dian' => '76364', 'nombre' => 'Jamundí'],
            ['codigo_dian' => '76377', 'nombre' => 'La Cumbre'],
            ['codigo_dian' => '76400', 'nombre' => 'La Unión'],
            ['codigo_dian' => '76403', 'nombre' => 'La Victoria'],
            ['codigo_dian' => '76497', 'nombre' => 'Obando'],
            ['codigo_dian' => '76520', 'nombre' => 'Palmira'],
            ['codigo_dian' => '76563', 'nombre' => 'Pradera'],
            ['codigo_dian' => '76606', 'nombre' => 'Restrepo'],
            ['codigo_dian' => '76616', 'nombre' => 'Riofrío'],
            ['codigo_dian' => '76622', 'nombre' => 'Roldanillo'],
            ['codigo_dian' => '76670', 'nombre' => 'San Pedro'],
            ['codigo_dian' => '76736', 'nombre' => 'Sevilla'],
            ['codigo_dian' => '76823', 'nombre' => 'Toro'],
            ['codigo_dian' => '76828', 'nombre' => 'Trujillo'],
            ['codigo_dian' => '76834', 'nombre' => 'Tuluá'],
            ['codigo_dian' => '76845', 'nombre' => 'Ulloa'],
            ['codigo_dian' => '76863', 'nombre' => 'Versalles'],
            ['codigo_dian' => '76869', 'nombre' => 'Vijes'],
            ['codigo_dian' => '76890', 'nombre' => 'Yotoco'],
            ['codigo_dian' => '76892', 'nombre' => 'Yumbo'],
            ['codigo_dian' => '76895', 'nombre' => 'Zarzal'],
        // Vaupés
            ['codigo_dian' => '97001', 'nombre' => 'Mitú'],
            ['codigo_dian' => '97161', 'nombre' => 'Caruru'],
            ['codigo_dian' => '97511', 'nombre' => 'Pacoa'],
            ['codigo_dian' => '97666', 'nombre' => 'Taraira'],
            ['codigo_dian' => '97777', 'nombre' => 'Papunaua'],
            ['codigo_dian' => '97889', 'nombre' => 'Yavaraté'],
        // Vichada
            ['codigo_dian' => '99001', 'nombre' => 'Puerto Carreño'],
            ['codigo_dian' => '99524', 'nombre' => 'La Primavera'],
            ['codigo_dian' => '99624', 'nombre' => 'Santa Rosalía'],
            ['codigo_dian' => '99773', 'nombre' => 'Cumaribo'],
        ];
        //SOURCE: https://dian-rut.com/dian/codigos-de-municipios/
        DB::table('ciudades')->insert($ciudades);
    }
}
